### ISSUE TITLE
Discussion: Background colour for radio buttons and checkboxes

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_elements#105]
Does the current background colour make radio buttons and checkboxes hard to see?

Should radio buttons and checkboxes also use a 2px dark grey border?

![form elements gov uk elements](https://cloud.githubusercontent.com/assets/417754/10302490/c052af7c-6c04-11e5-9073-ceb9bd401f67.png)

![form elements name](https://cloud.githubusercontent.com/assets/417754/10302541/2245febe-6c05-11e5-929f-b46277e62a29.png)

Is the 'selected' style for radio buttons and checkboxes too similar to the styles for form controls (white background, black border).

![pic23281](https://cloud.githubusercontent.com/assets/417754/10302909/d42deae0-6c07-11e5-8650-b079e5d3cc23.gif)

**Comment by edwardhorsford** [comment]
We're happy to add these in for our next user-research session on Monday.

My gut would be that the change is small enough that it won't make any difference either way.

**Comment by gemmaleigh** [comment]
Having spoken to @aduggin about this, he recommended that colour contrast for the border should pass AAA for large text, which it does.

Using $grey-1 (#6F777B) for the border.

Foreground: #6F777B - Background: #FFFFFF

The contrast ratio is: 4.56:1

Text passed at level AA
Text failed at level AAA
Large text passed at level AA
Large text passed at level AAA

1.4.3 Contrast (Minimum):  Text (and images of text) have a contrast ratio of at least 4.5:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 3:1. (Level AA)

1.4.6 Contrast (Enhanced): Text (and images of text) have a contrast ratio of at least 7:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 4.5:1. (Level AAA)

If everyone is in agreement about this, i'll merge #104 and close this issue.

@aduggin, @timpaul, @edwardhorsford.

**Comment by cjforms** [comment]
There are two different sorts of border here:
- ones that show you the box you can type into. These need a good contrast.
- ones that hint at the clickable area around the radio buttons/checkboxes. Please don't make these have even more visual noise on the page. Many users aim for the targets and it's hard enough to see the targets as it is - adding a strong border makes the targets even less visible. I'd much rather see the contrast of the targets increased and the border of the background hint text for the clickable area removed altogether.

**Comment by gemmaleigh** [comment]
Hi @cjforms, thanks - I moved the comment to #107.

The background colour for radio buttons and checkboxes will remain the same (without a darker border), the border width will increase and be darker for form controls you can type into.

**Comment by cjforms** [comment]
Splendid, thanks

**Comment by gemmaleigh** [comment]
Closing for now.
