### ISSUE TITLE
Colour contrast for borders on form elements

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_elements#107]
We currently recommend using `$grey-2` (1.81:1 contrast) for borders on form elements. It has been suggested that the contrast is not sufficient and that the 1px border width is too thin.

Propose increasing the border width to 2px.

If this not sufficient, it may well be necessary to also darken the border colour to `$grey-1` (4.56:1 contrast).

A pull request for this change can be found in #104.

Awaiting feedback from Edward Horsford @edwardhorsford  at passports (in user research 12/10/15) and Simon Wilson from Inheritance Tax.

**Comment by timpaul** [comment]
For reference, here's what it will look like:

![image](https://cloud.githubusercontent.com/assets/1590604/10340904/329b1c30-6d0a-11e5-84a3-d01ba34262b0.png)

**Comment by gemmaleigh** [comment]
The current border style:

![form elements before gov uk elements](https://cloud.githubusercontent.com/assets/417754/10302231/3d1c16a4-6c02-11e5-9bdc-b40f970de3b3.png)

With a darker colour and thicker border:

![form controls gov uk elements](https://cloud.githubusercontent.com/assets/417754/10302222/289ab7c6-6c02-11e5-87fd-249246eb86a8.png)

**Comment by gemmaleigh** [comment]
Having spoken to @aduggin about this, he recommended that colour contrast for the border should pass AAA for large text, which it does.

Using $grey-1 (#6F777B) for the border.

Foreground: #6F777B - Background: #FFFFFF

The contrast ratio is: 4.56:1

Text passed at level AA
Text failed at level AAA
Large text passed at level AA
Large text passed at level AAA

1.4.3 Contrast (Minimum):  Text (and images of text) have a contrast ratio of at least 4.5:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 3:1. (Level AA)

1.4.6 Contrast (Enhanced): Text (and images of text) have a contrast ratio of at least 7:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 4.5:1. (Level AAA)

If everyone is in agreement about this, i'll merge #104 and close this issue.

@aduggin, @timpaul, @edwardhorsford.

**Comment by edwardhorsford** [comment]
I have no complaint with this, though will reiterate that it's so close to our text colour that it could just be our text colour.

As it stands it's still an improvement, so I support this change.

**Comment by cjforms** [comment]
I agree with Ed on this. 
(My concerns are about adding strong borders to the hint for clickable area around radio buttons and checkboxes - a different matter)

**Comment by gemmaleigh** [comment]
Closing this issue, as #104 has been merged.
