### ISSUE TITLE
Add example of meta-data

### ISSUE THREAD

**Issue by pmackay** [alphagov/govuk_elements#108]
Most gov.uk pages have `meta-data` items like 

> Last updated: 15 October 2015 

on them but I cannot see this in the typography elements.

**Comment by gemmaleigh** [comment]
Hi @pmackay,

The GOV.UK Components Guide has a metadata component:
http://govuk-component-guide.herokuapp.com/components/metadata

Here is the scss for the metadata component:
https://github.com/alphagov/static/blob/master/app/assets/stylesheets/govuk-component/_metadata.scss
