### ISSUE TITLE
Make default table text size the same as body copy

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_elements#121]
We should assume that table text is the same 19px size as standard body copy, unless specified otherwise. Would be nice if the .font-xsmall class could be applied to an entire table though.

**Comment by gemmaleigh** [comment]
Following the discussion in the front end meeting. we'll keep the text size for tabular data at 14px for smaller screens, 16px for tablet and up and for special cases, for example - the "Check your answers" pattern, the text size will be increased to the standard body copy size of 19px.

**Comment by edwardhorsford** [comment]
@gemmaleigh I missed the frontend meeting. Could you summarise the discussion / the points for and against?

**Comment by gemmaleigh** [comment]
@timpaul @edwardhorsford, [here's the PR to increase the font size for tables to 19px](https://github.com/alphagov/govuk_elements/pull/185), so tabular data is the same size as body copy. 

It also adds a new `.table-font-xsmall` class (as Tim suggested) to recreate GOV.UK style smaller tables.

**Comment by gemmaleigh** [comment]
#185 fixes this.
