### ISSUE TITLE
Hide code snippets when JavaScript is disabled.

### ISSUE THREAD

**Issue by gemmaleigh** [alphagov/govuk_elements#151]
[Prism.js](http://prismjs.com/) is used to format and style the code snippets. 

When JavaScript is disabled, hide the code snippets.

**Comment by timpaul** [comment]
Is there any way of escaping the snippets so they still output without JavaScript? No worries if not - given that people can always view source it's not essential to offer snippets to non-JS users.

**Comment by joelanman** [comment]
is it bad to show the snippets without formatting? The content might still be useful to people
