### ISSUE TITLE
Make govuk_elements SASS it's own module

### ISSUE THREAD

**Issue by easternbloc** [alphagov/govuk_elements#155]
It'd be really neat to be able to install just the SASS from govuk elements much in the same way as the govuk_frontend_toolkit

So probably using npm we could have something like:

```bash
npm install --save govuk_elements_sass
```

We are currently copying it and other people are installing _all_ of elements just to get at the SASS so making this into it's own module would solve lots of problems.

**Comment by devtedd** [comment]
In the meantime would a viable solution be to add the elements project as an npm dependency:

    "govuk-elements": "git+https://github.com/alphagov/govuk_elements.git#v.1.0.0",

And then build your css using node-sass like:

    node-sass --output-style=expanded --include-path=node_modules/govuk_frontend_toolkit/stylesheets --include-path=node_modules/govuk-elements/public/sass node_modules/govuk-elements/public/sass/_govuk-elements.scss public/stylesheets/govuk-elements.css

Although having an npm package for the sass would be neater.

**Comment by gavboulton** [comment]
This would be an option now that the package is going to be versioned. Previously, the code was updated but not the version.
