### ISSUE TITLE
Missing the latest frontend toolkit sass

### ISSUE THREAD

**Issue by JoeChapman** [alphagov/govuk_elements#164]
It seems to me that the package is still missing the latest frontend toolkit sass from here https://github.com/alphagov/govuk_frontend_toolkit/tree/master/stylesheets

I can’t work out from the docs if the user is supposed to manually copy the files over.

**Comment by gemmaleigh** [comment]
Hi @JoeChapman.

The package has version 4.6.0 of the govuk front end toolkit as a dependency.

    npm install govuk-elements-sass
    npm http GET https://registry.npmjs.org/govuk-elements-sass
    npm http 304 https://registry.npmjs.org/govuk-elements-sass

    npm http GET https://registry.npmjs.org/govuk_frontend_toolkit
    npm http 304 https://registry.npmjs.org/govuk_frontend_toolkit
    govuk-elements-sass@1.1.1 node_modules/govuk-elements-sass
    └── govuk_frontend_toolkit@4.6.0

The files in `/node_modules/govuk-elements-sass/node_modules/govuk_frontend_toolkit/stylesheets` need to be in the same location as the govuk-elements sass files.

You're right, this isn't clear - I'll update the docs.

You can either copy the files over, or use Grunt's 'includePaths: option`, the [GOV.UK prototype kit has an example of this](https://github.com/alphagov/govuk_prototype_kit/blob/master/Gruntfile.js#L14).

**Comment by gemmaleigh** [comment]
Hi @JoeChapman, I think this has now been resolved.

The govuk_frontend_toolkit is included as a dependency and is installed to /node_modules/ when the 'govuk-elements-sass' module is installed.

Let me know if it doesn't work for you and I'll re-open.
