### ISSUE TITLE
Radio buttons jump up and down on Safari when activated

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_elements#166]
Radio buttons, when activated drop down by about 10 pixels in Safari 8 and 9 on OS X. They jump back up to their original positions when the animation ends.

([filed the original issue in the wrong place](https://github.com/alphagov/govuk_frontend_toolkit/issues/221))

**Comment by gemmaleigh** [comment]
Removing the width and height for the input fixes this (as in Safari, the width and height don't increase the size of the form control).

**Comment by gemmaleigh** [comment]
#296 fixes this.

**Comment by PanosParalakis** [comment]
Removing the width or height for the input fixes this but  the position is changed. Position had to be updated as well. I have made a pull request which is fixing this #323 .

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/alphagov/govuk_elements/pull/296 (and released in elements 2.2.0)
