### ISSUE TITLE
Error validation summary guidance leads to repetition

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#177]
If you follow both our validation guidance, and our guidance to have 'one thing per page', I'm concerned that you'll end up with redundant repetition on the page.

For example, if there's one thing on the page: "What is your national insurance number?", then the summary error and the field error will be the same.

Is there a way to make this situation accessible (eg using a visually hidden element, or focusing the field error) without adding redundant elements to the page?

An example:

![image](https://cloud.githubusercontent.com/assets/1132904/13143969/58de8050-d63f-11e5-8236-b8d8b916fec4.png)

**Comment by cjforms** [comment]
When Gemma and I were first working on the error message guidance, we wanted to say 'if there's only one question on the page then you don't need a summary box'. I think we dropped it because the advice was getting complicated. Might be a good time to revisit that decision.

**Comment by gemmaleigh** [comment]
I think there's a clear advantage to always having a summary box for users of assistive technology. This is why we decided to keep summary boxes, even when there's only one question per page.

The advantage is that the error message is prominent, it appears as one of the first items on the page and provides a link as a shortcut to allow the error message to be easily reached and corrected. 

Ideally, the repetition you see here would be solved by changing the wording of the error messages.

The first would give an indication that an error has occurred 'You must answer the question', the second would indicate what the error is and how to resolve it 'Choose how you would like to get your photo'.

**Comment by joelanman** [comment]
Yeh I definitely get the advantages for assistive tech, and thats crucial. Was just wondering if it's at all possible to keep that support, and avoid the visual repetition. In your example, the repetition would move from the 2 error messages to the error message and the label - both would be (slight variant on) "how you would like to get your photo?"
