### ISSUE TITLE
Could you add a section on 'panels'? 

### ISSUE THREAD

**Issue by roc** [alphagov/govuk_elements#179]
I was expecting a small bit of guidance around `panels` in the [form elements](http://govuk-elements.herokuapp.com/form-elements/) section of the guide.

They get used inside the Errors and validation section (see screenshot), and there are examples of using `panel panel-border-narrow` in the 'Conditionally revealing content' section of the [form elements](http://govuk-elements.herokuapp.com/form-elements/). This is cool, but it's a bit hidden away.

Could you add a section on how to and where to use panels?

![screen shot 2016-02-19 at 12 20 13](https://cloud.githubusercontent.com/assets/120181/13175731/54e292c8-d704-11e5-9794-d01b49599c97.png)

**Comment by sanjaypoyzer** [comment]
I'm not sure this is a "form element" as such. There is a section for this pattern under [Inset Text on the Typography page](http://govuk-elements.herokuapp.com/typography/#typography-inset-text). Possibly there's a need to link to that section in the form elements page?

**Comment by gemmaleigh** [comment]
#212 fixes this.
