### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk_elements#205]
Is there any chance of including release notes (e.g. whats changed and any bug fixes) when a new version is released([https://github.com/alphagov/govuk_elements/releases/tag/v1.1.4](https://github.com/alphagov/govuk_elements/releases/tag/v1.1.4))? 

This should be fairly easy to do inside github (https://github.com/alphagov/govuk_elements/releases) where it allows you to create draft release and for you to add to it as PR are merged.

Here is an example of release notes https://github.com/firebug/websocket-monitor/releases/tag/websocketmonitor-0.5.3

This would help when it comes to updating [other projects](https://github.com/ministryofjustice/govuk_elements_rails) that rely on govuk_elements and things to look out for that could potentially break like additional files added/removed or even restructured to govuk_elements

**Comment by aliuk2012** [comment]
Actually this should just be a case of copy the content from https://github.com/alphagov/govuk_elements/blob/master/CHANGELOG.md and place it into GitHub Releases https://github.com/alphagov/govuk_elements/releases

**Comment by gemmaleigh** [comment]
Hi @aliuk2012, apologies for the slow reply, I've been away.

I've now updated the two most recent releases and i'll update the rest later today. https://github.com/alphagov/govuk_elements/releases

**Comment by gemmaleigh** [comment]
The contents of the CHANGELOG.md have been copied to the releases. 
https://github.com/alphagov/govuk_elements/releases

Closing as this issue is now resolved.
