### ISSUE TITLE
Example of errors for date fields

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk_elements#206]
Currently there are no examples of where errors should be presented or how they should be presented.

My initial thought were that it would be between the day/month/year labels and the fields but what if the validations only relate to one part of the date like an invalid month.

Any other suggests?

This is taken from Register to Vote
![image](https://cloud.githubusercontent.com/assets/3441519/14172969/0b75309c-f733-11e5-95f4-6a53df2785c5.png)

**Comment by aliuk2012** [comment]
Some more examples:
this is the “Apply for a budgeting loan” service, in private beta at the moment 
<img width="512" alt="screen shot 2016-03-31 at 11 34 26" src="https://cloud.githubusercontent.com/assets/3441519/14173398/8a08e8e8-f735-11e5-92a4-a0face962d92.png">


This is Money to Prisoners service
<img width="602" alt="screen shot 2016-03-31 at 11 28 04" src="https://cloud.githubusercontent.com/assets/3441519/14173408/9c809048-f735-11e5-9ea1-b950a208a016.png">

**Comment by joelanman** [comment]
the Money to Prisoners example seems a bit overkill - I think the red line on the left for the question, and the border on the fields is sufficient.

I _think_ Register to vote is displaying the error underneath the field because it's handled by javascript, so it shows the error, but avoids jumping the user up the page unexpectedly.

The Apply for a budgeting loan example is the normal, server side pattern.

**Comment by glenjamin** [comment]
For reference, apply for a budgeting loan's validation is client-side, but our client-side validation matches the server side validation in logic and display.

When errors are triggered we jump to the top and role="alert" all the validations that have appeared.

**Comment by joelanman** [comment]
@glenjamin cheers for clarifying :)

**Comment by gemmaleigh** [comment]
#229 fixes this.

**Comment by gemmaleigh** [comment]
Fixed by #229. The examples can be seen here: http://govuk-elements.herokuapp.com/form-elements/example-form-elements/
