### ISSUE TITLE
Some colours aren't shown

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#207]
Some colours from the palette aren't shown on the Colour page - eg. light-blue-25. Is this intentional?

https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/colours/_palette.scss

**Comment by gemmaleigh** [comment]
Good question, I'm not sure where the -25 and -50 colours are used.

http://govuk-elements.herokuapp.com/colour#colour-extended-palette

They are mentioned in the bullet point above the extended palette 
- "for tints of the extended palette, use 25% or 50%" but they're not shown as swatches.

@markhurrell, any idea where these might be used?

Would it be useful to add these as colour swatches shown here?

**Comment by joelanman** [comment]
We recently used one of these on the EU referendum banner, and I think the cookie banner uses it too (light blue?)

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
