### ISSUE TITLE
Example of 'Conditionally revealing content'

### ISSUE THREAD

**Issue by pietrodesiato** [alphagov/govuk_elements#211]
The provided example on [this page](http://govuk-elements.herokuapp.com/form-elements/#form-toggle-content) is : 
'<h1 class="heading-medium">
    Do you know their National Insurance number?
  </h1>

  <form>
    <fieldset class="inline">

      <legend class="visuallyhidden">Do you know their National Insurance number?</legend>

      <div class="form-group">

        <label class="block-label" data-target="example-ni-no" for="radio-indent-1">
          <input id="radio-indent-1" type="radio" name="radio-indent-group" value="Yes">
          Yes
        </label>

        <label class="block-label" for="radio-indent-2">
          <input id="radio-indent-2" type="radio" name="radio-indent-group" value="No">
          No
        </label>

        <div class="panel panel-border-narrow js-hidden" id="example-ni-no">
          <label class="form-label" for="national-insurance">National Insurance number</label>
          <input class="form-control" name="national-insurance" type="text" id="national-insurance">
        </div>

      </div>

    </fieldset>
  </form>
'

The 'No' label is missing the `data-target="example-ni-no" ` attribute

**Comment by gemmaleigh** [comment]
The `data-target="example-ni-no"` attribute is present on the "Yes" label, so if you know the NI number, you can enter it and if you don't know the NI number, you aren't then asked to fill in an additional field.

**Comment by sanjaypoyzer** [comment]
Maybe that clarification should be added on the guidance?

**Comment by gemmaleigh** [comment]
The text above, says:

**Conditionally revealing content**

* reveal additional questions, depending on the context

Click on "Yes" below to see how this works.

**Comment by pietrodesiato** [comment]
If I use that code and then I click 'No', the conditional field won't disappear

**Comment by gemmaleigh** [comment]
Hi @pietrodesiato, if you could share a link to your code with me - I can take a look and see if I can help.

**Comment by gemmaleigh** [comment]
For this to work, you'll need the JavaScript used by GOV.UK elements to add a .js-hidden class, which will hide this content.

The styles for this are set by the [GOV.UK template](https://github.com/alphagov/govuk_template/blob/86106bfb332ff5c0346b92310a4117daeb2d8c8d/source/assets/stylesheets/_accessibility.scss#L18):

```
.js-enabled .js-hidden {
  display: none;
  visibility: hidden;
}
```

The [JavaScript responsible for adding the the .js-hidden class is here](https://github.com/alphagov/govuk_elements/blob/master/public/javascripts/application.js#L37).

Hope that helps.

**Comment by pietrodesiato** [comment]
I copy and pasted the code in the example and it's not working for me: the conditional div is showing when clicking 'Yes' but it does not hide when clicking 'No'.

I looked at the html and the 'Yes' has this additional attribute that is not mentioned in the code example: `aria-controls="example-ni-no" `

**Comment by gemmaleigh** [comment]
The `aria-controls` attribute is there to provide additional information to screenreaders, so that they can set focus to the revealed content when it is opened. 

It creates a relationship between the control and the content which is toggled.

http://tink.uk/using-the-aria-controls-attribute/
https://www.w3.org/TR/wai-aria/states_and_properties#aria-controls

Have you checked that your JS matches what is here?
https://github.com/alphagov/govuk_elements/blob/master/public/javascripts/application.js#L10

**Comment by pietrodesiato** [comment]
I checked the elements applications.js and the prototyping toolkit application.js (which I am currently using) and they have some significant differences that might affect this specific behaviour.

The kit is using show() and hide() while elements are adding or removing the CSS js-hidden class.

**Comment by pietrodesiato** [comment]
ELEMENTS:

` // Hide toggled content
            $groupDataTarget.addClass('js-hidden');
            // Set aria-expanded and aria-hidden for hidden content
            $this.attr('aria-expanded', 'false');
            $groupDataTarget.attr('aria-hidden', 'true');
          });

          var $dataTarget = $('#' + dataTarget);
          $dataTarget.removeClass('js-hidden');
          // Set aria-expanded and aria-hidden for clicked radio
          $radio.attr('aria-expanded', 'true');
          $dataTarget.attr('aria-hidden', 'false');

        });`

PROTOTYPING KIT

` // Hide toggled content
            $groupDataTarget.hide();
            // Set aria-expanded and aria-hidden for hidden content
            $this.attr('aria-expanded', 'false');
            $groupDataTarget.attr('aria-hidden', 'true');
          });

          var $dataTarget = $('#' + dataTarget);
          $dataTarget.show();
          // Set aria-expanded and aria-hidden for clicked radio
          $radio.attr('aria-expanded', 'true');
          $dataTarget.attr('aria-hidden', 'false');
`

**Comment by gemmaleigh** [comment]
[There is a pull request which fixes those differences for the prototype kit](https://github.com/alphagov/govuk_prototype_kit/pull/176/files), it hasn't been merged yet.

**Comment by gemmaleigh** [comment]
Hi @pietrodesiato, @joelanman merged that PR, so if you update your version of the prototype kit - that example will work for you.

There's also another working example here: http://govuk-prototype-kit.herokuapp.com/examples/elements/toggled-content

**Comment by gemmaleigh** [comment]
#212 fixes this.
