### ISSUE TITLE
Proposal: Add elements for Printing / Downloadable documents

### ISSUE THREAD

**Issue by sanjaypoyzer** [alphagov/govuk_elements#216]
There's some patterns [here](https://designpatterns.hackpad.com/Printing-downloadable-documents-BNDJeJ40tKU) for downloadable documents. Would probably make sense if they were in this repo?

I mainly think so because I've just added the download link into a prototype I'm working on by copying over the SCSS and the icon, so it seems like it would save time.

**Comment by gemmaleigh** [comment]
The icons in the front-end toolkit are shown here:
http://govuk-elements.herokuapp.com/icons-images/example-icons/

The download icon is provided, but the [styles for download icons with text next to them](https://github.com/alphagov/static/blob/e08e2bd07c81f03b7de73e59f10843531c81c541/app/assets/stylesheets/helpers/_text.scss#L424) don't yet sit as part of GOV.UK elements. 

It's likely that if they are a commonly used GOV.UK pattern, they would be added to the GOV.UK component guide as part of the front end refactoring work. 

There hasn't been a precedent for copying these patterns to GOV.UK elements, however Tim's going to be looking into how all this fits together as part of the Service Design programme.

cc. @timpaul.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

There is an [issue in the Design System backlog for download links](https://github.com/alphagov/govuk-design-system-backlog/issues/20) which has some more discussion around this.
