### ISSUE TITLE
Consider removing type attributes and removing self-closing tags

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#218]
It would be good to remove type attributes as they are not required in a HTML5 document.

It would also be good having consistency. In some cases we have self closing tags and in other cases not. They are not required in a HTML5 document.

**For example:**
rel="stylesheet" />
rel="stylesheet">

**Comment by gemmaleigh** [comment]
Thanks @trevorsaint you're absolutely right, [this work has been carried out for the GOV.UK template](https://github.com/alphagov/govuk_template/pull/208), but not here. 

My personal preference is to keep the self closing tags, but I'll be sure to check use of them is consistent.

**Comment by gemmaleigh** [comment]
Upon further investigation, it looks like some of this work has been carried out for the GOV.UK template - the redundant type attributes have either been removed [or will soon be removed](https://github.com/alphagov/govuk_template/pull/219/commits/0fc390dcc7fdf75cd1c4c95f3e8164300ffed0c8).

Checking the self closing tags isn't a high priority for us right now, but we'll review a pull request for the GOV.UK template if you would like to open one. 👍
