### ISSUE TITLE
Form label and hint inside a fieldset

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#222]
I think some improvements need to be made for form labels and hints within a fieldset for example a YES/NO question.

In the examples presented. All checkboxes, radio buttons have effectively a medium title which is all very nice for questions that follow the radio or checkbox structure. (Single page questions)

The problem I have found is when you work with standard form inputs and introduce radios etc... you need consistency with the form patterns for everything as an example:

http://onlineplea.herokuapp.com/#/your-details

This page demonstrates consistency, however I have had to add a hack which I am not proud of. Perhaps time can be spent looking into this issue:

**CSS**
```
.form-hint {
  margin-bottom: 0;
  padding-bottom: em(7);  
}

legend span ~ span {
  margin-top: em(-7);
} 
```

**HTML**

```
<legend>
   <span class="form-label-bold">Label</span>
   <span class="form-hint">Help</span>
</legend>
```

This fixes spacing issues. But I don't like it.

Perhaps I have missed something, or approached this the wrong way. Any advice and or direction would be good.

**Comment by joelanman** [comment]
Hi @trevorsaint, sorry I can't quite follow what the issue is - is this to do with vertical spacing in different scenarios?

**Comment by trevorsaint** [comment]
@joelanman Absolutely.

**Comment by gemmaleigh** [comment]
Hi @trevorsaint, I'll take a look at this today.

I was using those two spans within a legend as a way to workaround [unreliable legend styling](http://www.456bereastreet.com/lab/styling-form-controls-revisited/legend/).

But I think it might be this [line which you're having to override](https://github.com/alphagov/govuk_elements/blob/master/public/sass/elements/_forms.scss#L88).

I'll create an example page and see if there's a better way to set the spacing underneath labels and hints (and those within legends).

**Comment by gemmaleigh** [comment]
#229 Fixes this.
