### ISSUE TITLE
Inline radio improvements (spacing)

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#224]
Inline radio buttons have a margin bottom of 15px. This margin is for spacing, if conditionally revealing content exists. Very nice.

The problem is when conditionally revealing content does not exist. Where we simply want a Yes/No answer. In this case it makes no sense to have a margin bottom value. And as a result, this puts the space consistency out of rhythm.

My suggestion would be to apply the margin top on the panel if it sits within an inline field set.

This would then fix the spacing issue for inline radio when no conditional content is required

**Comment by trevorsaint** [comment]
A little more work is required due to issues with clearing.

**Comment by sanjaypoyzer** [comment]
Hi Trevor, could you add a screenshot to show what you mean? Thanks.

**Comment by gemmaleigh** [comment]
Hi Trevor,

I'm taking a look at this now. I've highlighted the .form-groups in pink to make it easier to see what you mean.

@sanjaypoyzer here's a screenshot in case you wanted to see where the additional spacing exists.

Before (without toggled content open):

![example form elements form elements gov uk elements](https://cloud.githubusercontent.com/assets/417754/15422790/137da0ba-1e72-11e6-9eb0-b0f22a92459d.png)

Before (with toggled content open):

![before - opened](https://cloud.githubusercontent.com/assets/417754/15422745/db4b7f28-1e71-11e6-9517-9fa709b4dcc6.png)

I've moved the margin top:15px to the toggled panel and removed the bottom margin from any .block-labels which are the only .block-label or the last .block-label in a .form-group. 

It feels pretty fragile, another solution might be to have an option to override the bottom margin on a block label. 

Here's a screenshot of the spacing now:

![after - example form elements form elements gov uk elements](https://cloud.githubusercontent.com/assets/417754/15422869/86a5e6ce-1e72-11e6-8529-ee842a30ec86.png)

![after - opened example form elements form elements gov uk elements](https://cloud.githubusercontent.com/assets/417754/15422873/89c18af2-1e72-11e6-8be6-87511080aaac.png)

Here's a [PR to fix this issue](https://github.com/alphagov/govuk_elements/pull/229)

Cheers!
Gemma

**Comment by gemmaleigh** [comment]
#229 fixes this.
