### ISSUE TITLE
Hidden text (progressive disclosure) improvements

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#226]
Something that has been bugging me about this control is the fact that if you double click on the link you get a selection highlight. Might I suggest we add the following attributes for the summary element.

```
.summary {
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
  }
```

This prevents the highlight on clicking the link.

Perhaps there is good reason why this has not been done, and if so I would love to know why. I understand that you can no longer make a selection of the link, but why would you need to. This is not content copy.

Thanks

**Comment by joelanman** [comment]
Not sure why you'd want to prevent selection of the link? Someone may want to highlight it for a screenshot, or copy and paste, etc.

**Comment by trevorsaint** [comment]
@joelanman I understand your point. Try clicking on it a few times. It feels wrong - [Example](http://govuk-elements.herokuapp.com/typography/)

In regards a screenshot - this should not be a problem.

Agreed if someone wanted to copy and paste text, this would pose a problem.

**Comment by joelanman** [comment]
It feels like this is the kind of thing a designer or developer would do rather than a real user - if you click twice fast enough to cause it, you can't read the content. We don't want to prevent copy and paste, so I think we'll probably close this PR.

**Comment by trevorsaint** [comment]
Sure thing @joelanman ;)
