### ISSUE TITLE
Different sized buttons

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk_elements#228]
Hi, is there any particular reason why the govuk element button class (https://github.com/alphagov/govuk_elements/blob/master/public/sass/elements/_buttons.scss#L7) 
uses different padding to the govuk frontend toolkits button mixin (https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/design-patterns/_buttons.scss#L30)

GOVUK Elements Button class:
```
padding: em(10) em(15) em(5);
```
GOVUK Frontend Toolkit Button mixin:
```css
padding: 0.3em 0.6em 0.2em;
```

GOVUK Elements button class calls GOVUK Frontend Toolkits button mixin and then overwrites the padding as above.

I’m happy to remove it from govuk elements, update govuk frontend so GOVUK Elements button class still has the same amount of padding and to pr it. Its just a pain to line up buttons when you use .button and then button mixin to create secondary buttons.
![screen shot 2016-05-20 at 09 10 18](https://cloud.githubusercontent.com/assets/3441519/15424796/741036b8-1e7c-11e6-89b1-50a427fc8c8d.png)

Any thoughts about it?

**Comment by gemmaleigh** [comment]
This is an example of one of the things which hasn't been propagated back up from GOV.UK elements to the GOV.UK front-end toolkit.

You're right, there's no reason why these two should be different. 

If you could please raise a pull request to increase the padding for buttons in the frontend toolkit, then this will be reflected everywhere and GOV.UK elements won't need to override those values.

**Comment by joelanman** [comment]
Making them all larger to match elements sounds right to me, bigger hit areas make it easier for users
