### ISSUE TITLE
The <abbr> tag and style

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#239]
What is the desired style of this tag?

In Chrome we have no underline and in Firefox we have a dotted border bottom. Because no styling has been applied other than cursor: help; I am under the impression this is how GDS want it.

Has this been missed? Should I set text-decoration: none on this element?

Any steer would be good.

Thanks

**Comment by gemmaleigh** [comment]
Hi Trevor,

The only example I can find of `<abbr>` styling is in the [GOV.UK component guide](http://govuk-component-guide.herokuapp.com/components/govspeak/fixtures/statistic_headlines/preview). 

This uses `cursor:help` which shows ? on hover and reveals the value of the title attribute.
`<abbr title="Departmental Expenditure Limit">DEL</abbr>`

`text-decoration: none` is also being applied, this isn't being copied to the reset used by GOV.UK elements.

For now, I'd use `text-decoration: none` and I'll add it to a list of things we should provide an example of.

**Comment by trevorsaint** [comment]
Hi Gemma. I don't need an example of it :). It was an observation. I would have added the styling myself, but wanted to know why it had not been added into Gov Elements. I will add this myself in the hope of removing it when it is in your reset file. Thanks.

**Comment by robinwhittleton** [comment]
@trevorsaint so the history is that `abbr` used to be styled in all browsers with `border-bottom: 1px dotted`. In W3’s [default HTML styles](https://www.w3.org/TR/html51/rendering.html#non-replaced-elements-phrasing-content) they suggest `text-decoration: dotted underline` instead. Firefox switched their user agent styles to match this when they added support for dotted underlines, but Chrome don’t so stuck with a dotted border. Our reset stylesheet on elements is out of date (on of the reasons I dislike them, but that’s another matter) so only resets border. We also need to reset the `text-decoration-style` ([as per the rest of GOV.UK](https://github.com/alphagov/static/commit/3042caaa277106f1493aeb60466239948ad4c8a4)), so I’ll do a PR for that now.
