### ISSUE TITLE
Enhancement to radio, checkboxes and conditionally revealing content 

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#240]
I have noticed that for all radios, checkboxes and conditionally revealing content they all assume no value has been chosen. In most cases this is good as it forces the user to make a choice. 

**What about the following scenario:**

A user returns to a page with the ability to update an already populated form, which may or may not include radios, checkboxes and conditionally revealing content based on form selection.

I would have expected that if the input has "checked" or checked="checked" then all required styling would be applied, but this does not look to be the case.

Is this something to be added in future releases?

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

Note that this has been implemented in GOV.UK Frontend – [if a radio or checkbox is checked then the conditional content associated with it should be visible on page load](https://github.com/alphagov/govuk-frontend/blob/fc45f6ff073756c91b8d163d0ee0a146feba640a/src/components/radios/template.test.js#L314-L338).
