### ISSUE TITLE
Inline class on the fieldset causing issues with the requirement for stacked items inside

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#246]
I have found in our service we have a requirement to have stacked radio options within an inline group of options of Guilty / Not guilty

Essentially placing a fieldset inside a fieldset which is totally fine. The problem is that the second fieldset block labels pick up the inline styling regardless of having no inline class associated with the second fieldset.

Do you have something in place to cater for this that I am not aware of?

I think this is a little too generic

`.inline .block-label`

I have worked around the problem by adding a new class with attributes to override the inherited attributes.

`.stacked .block-label`

![example](https://cloud.githubusercontent.com/assets/4989027/15775398/a0e9318c-2979-11e6-8a8a-52791fb4c544.png)

**Comment by trevorsaint** [comment]
![example](https://cloud.githubusercontent.com/assets/4989027/15772978/54d7f344-296c-11e6-9a42-7f4dda81bc1d.png)

**Comment by robinwhittleton** [comment]
Can you move the `inline` class further down your tree? For example, you could have a `<fieldset class="inline">` that wraps just the guilty / not guilty questions and doesn’t include the further questions.

**Comment by trevorsaint** [comment]
Hi Rob. Yes I could do that. Will give it a try this morning and see how that goes.

**Comment by robinwhittleton** [comment]
Did that help? Will close this issue if it did.

**Comment by gemmaleigh** [comment]
Hi @trevorsaint, did @robinwhittleton's suggestion fix your issue? Please let us know so we can close this issue, thanks!

**Comment by gemmaleigh** [comment]
Hi @trevorsaint, I'm hoping @robinwhittleton's suggestion fixed your issue. Please re-open if not.
