### ISSUE TITLE
Borders on inputs have low contrast if colours adjusted by user

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#297]
If a user adjusts their colours (for accessibility / readability), many bits of elements colours change, but input borders don't (in firefox at least). Similarly, buttons become invisible, as do warning graphic icons.

Screenshot:
![screen shot 2016-08-30 at 12 30 05](https://cloud.githubusercontent.com/assets/2204224/18087510/8406dabe-6ead-11e6-91e9-2bdfb20f7f83.png)
## How would you expect it to work?

It would be great if the borders adjusted with text colour. It looks like other graphic elements _do_ change - such as the 'examples' border.
## How does it work currently?

The border of inputs does not change.
## Feel free to suggest a fix...

Might not have a fix - but raising an issue in case it can be improved.

Tested after re-reading [this](https://accessibility.blog.gov.uk/2016/05/26/accessibility-and-me-marian-foley/) blog post: 
## Explain the steps to reproduce the bug

Use firefox to adjust text and background colours.

**Comment by edwardhorsford** [comment]
More examples:
![screen shot 2016-08-30 at 12 34 55](https://cloud.githubusercontent.com/assets/2204224/18087714/73ceb580-6eae-11e6-926d-b3187179daae.png)
![screen shot 2016-08-30 at 12 35 15](https://cloud.githubusercontent.com/assets/2204224/18087719/78f392a6-6eae-11e6-97ed-a76fd399c869.png)

**Comment by gemmaleigh** [comment]
#296 fixes this, these will now inherit  `$text-colour`, so they can be overridden.

**Comment by robinwhittleton** [comment]
Fixed by #296
