### ISSUE TITLE
Checkbox labels not read out in VoiceOver/Chrome

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_elements#312]
@cfq found that checkbox labels aren’t read in VoiceOver on Chrome. This is the case with the current versions and with the new designs. They work in VoiceOver on Safari suggesting a Chrome bug, but it would be good to work around this in our code if possible.
## How would you expect it to work?

VoiceOver reads something like ‘Checkbox, unchecked, label text for checkbox’
## How does it work currently?

VoiceOver reads ‘Checkbox, unchecked’
## Explain the steps to reproduce the bug
1. Load the [govuk_elements checkbox examples](http://govuk-elements.herokuapp.com/form-elements/#form-checkboxes) in Chrome with VoiceOver
2. Listen to it read them
3. Contrast with the same page that works in Safari with VoiceOver

**Comment by robinwhittleton** [comment]
Turned out this broke in Chrome 53. Filed a Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=646846

**Comment by nickcolley** [comment]
They've marked this as fixed, so ready for us to re-test.

**Comment by gemmaleigh** [comment]
I've asked @cfq if he can confirm this has been fixed, as part of the accessibility audit of the elements snippets.

**Comment by robinwhittleton** [comment]
In my quick testing, it was still broken in Chrome 54 but fixed in Chrome 56.

**Comment by cfq** [comment]
Also checked in Chrome Canary which is Chrome 56 - works fine. The [estimated release date for 56](https://www.chromium.org/developers/calendar) is currently 31st of Jan, 2017.

**Comment by igloosi** [comment]
we're now on chrome 58 so closing this issue
