### ISSUE TITLE
Form focus states not identical in all browsers

### ISSUE THREAD

**Issue by 20Fourteen** [alphagov/govuk_elements#324]
While perusing some Government websites on different browsers I noticed that form focus states are not identical in all browsers.

See below screen recording, and note the browsers.

![govuk](https://cloud.githubusercontent.com/assets/8763290/19126034/3362cec4-8b31-11e6-837c-c23e36094cdd.gif)

(tested on Windows and Mac, but recording was on Windows)

What is the intended design?

**Comment by edwardhorsford** [comment]
@nickcolley I think it fixes it.

**Comment by gemmaleigh** [comment]
These focus styles are set by the govuk_template, once [PR #259](https://github.com/alphagov/govuk_template/pull/259) has been merged, the steps to fix this for govuk_elements are:

- [ ] Bump the version of govuk_template
- [ ] Update the version of govuk_template_jinja that govuk_elements is using to pull in this change
- [ ] Update `_govuk-template-base.scss`, this file duplicates the base styles set by govuk_template, for anyone consuming govuk-elements-sass without govuk-template.

**Comment by robinwhittleton** [comment]
Will be fixed in the next release. Thanks for the report!
