### ISSUE TITLE
Unable to import scss files into Angular2 CLI

### ISSUE THREAD

**Issue by hbweb** [alphagov/govuk_elements#334]
## How would you expect it to work?

I'm unable to import govuk elements sass files into Angular2 CLI project.. as it does not know where to look for partial scss files with underscore prefix.. It could just be Angular CLI bug..However, I've been trying many different ways but no luck so far.

Any indication to get it work would be much appreciated. 

Thanks
## How does it work currently?

With angular cli, we can reference the SCSS file to 'styles' attribute. 

> Please provide us with the following information:
> I'm unable to import SCSS partial files into Angular CLI and getting error when running `ng serve` 
### OS?

Windows 10 (Win32 x64)
angular-cli: 1.0.0-beta.17
node: 6.9.1
os: win32 x64
### Versions.

angular-cli: 1.0.0-beta.17
node: 6.9.1
npm: 3.10.8
### Repro steps.
1. Install Gov.uk npm package from https://github.com/alphagov/govuk_elements

`npm install govuk-elements-sass --save`
1. Include scss files into angular-cli.json file

`
"styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/govuk-elements-sass/public/sass/_govuk-elements.scss",
        "styles.scss"
      ],
`
### The log given by the failure.

`
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./~/govuk-elements-sass/public/sass/_govuk-elements.scss
Module build failed:
undefined
^
      File to import not found or unreadable: colours
Parent style sheet: stdin
      in D:\workspace\dnaapp\node_modules\govuk-elements-sass\public\sass\_govuk-elements.scss (line 6, column 1)
 @ ./~/govuk-elements-sass/public/sass/_govuk-elements.scss 4:14-147
 @ multi styles
`

**Comment by gemmaleigh** [comment]
Hi there! 

It looks like you're not including the partials from the govuk_frontend_toolkit that govuk_elements depends on. 

You'll need these partials from the [govuk_frontend_toolkit](https://github.com/alphagov/govuk_frontend_toolkit/tree/master/stylesheets), these are imported at the top of the `_govuk-elements.scss` file. 

```
// GOV.UK frontend toolkit
// Sass variables, mixins and functions
// https://github.com/alphagov/govuk_frontend_toolkit/tree/master/stylesheets

// Settings (variables)
@import "colours";                                 // Colour variables
@import "font_stack";                            // Font family variables
@import "measurements";                     // Widths and gutter variables

// Mixins
@import "conditionals";                          // Media query mixin
@import "device-pixels";                        // Retina image mixin
@import "grid_layout";                            // Basic grid layout mixin
@import "typography";                           // Core bold and heading mixins
@import "shims";                                    // Inline block mixin, clearfix placeholder

// Mixins to generate components (chunks of UI)
@import "design-patterns/alpha-beta";
@import "design-patterns/buttons";

// Functions
// @import "url-helpers";                         // Function to output image-url, or prefixed path (Rails and Compass only)
```

There's some [guidance on compiling the sass files as part of your build process here](https://github.com/alphagov/govuk_elements#using-a-task-runner-to-compile-the-sass-files). 

Let me know if that resolves this issue for you!

**Comment by hbweb** [comment]
Hello @gemmaleigh ,

Thanks for getting back to me. I've been playing with it and following your suggestion to include all partials from the **govuk_frontend_toolkit** , however, I'm still getting the same error message .

angular-cli.json
``` 
      "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",

        "../node_modules/govuk_frontend_toolkit/stylesheets/_colours.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_font_stack.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_measurements.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_conditionals.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_device-pixels.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_grid_layout.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_typography.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_shims.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_helpers.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_url-helpers.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/_css3.scss",

        "../node_modules/govuk_frontend_toolkit/stylesheets/design-patterns/_alpha-beta.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/design-patterns/_buttons.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/design-patterns/_breadcrumbs.scss",
        "../node_modules/govuk_frontend_toolkit/stylesheets/design-patterns/_media-player.scss",

        "../node_modules/govuk-elements-sass/public/sass/_govuk-elements.scss",
        "styles.scss"
      ],
```
Same error message when keeping the same _govuk-elements.scss file

```
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./~/govuk-elements-sass/public/sass/_govuk-elements.scss
Module build failed:
undefined
^
      File to import not found or unreadable: colours
Parent style sheet: stdin
      in D:\workspace\dnaapp\node_modules\govuk-elements-sass\public\sass\_govuk-elements.scss (line 6, column 1)
 @ ./~/govuk-elements-sass/public/sass/_govuk-elements.scss 4:14-147
 @ multi styles
```

Since all partials has been included, should I remove the `@import`  from _govuk-elements.scss file?

Thanks

**Comment by gemmaleigh** [comment]
Hi @hbweb, 

If the error message hasn't changed, I'd guess that those partials aren't available to the govuk-elements sass files. 

From the error message above, we think you might be using WebPack.

You'll need to configure the includePaths option, to include the paths to the govuk_frontend_toolkit, when compiling the govuk-elements sass files.

https://github.com/jtangelder/sass-loader#sass-options
```

module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
    ]
  },
  sassLoader: {
    includePaths: [path.resolve(__dirname, "./some-folder")]
  }
};

```
Don't remove anything from the ` _govuk-elements.scss` file, this file exists as a manifest to load in everything you'll need, it's best not to modify it.

**Comment by hbweb** [comment]
Hi Gemma,

Yes, you're right. [Angular CLI](https://github.com/angular/angular-cli) use Webpack atm and we can include scss files to compile in angular-cli.json file. I won't be able to change anything else otherwise as it will be overwritten when angular cli package get upgraded. 

I will look into this further as I feel that we are getting some where atm.

Cheers

**Comment by hbweb** [comment]
Good morning @gemmaleigh ,

I can now see why Govuk frontend toolkit scss dependencies does not get included as they get saved in different folder inside **node_modules**.
The `_govuk-elements.scss` file import these dependencies using relative path (where it requires these partial files to be in the same folder to get resolved) .. Hence the current files structure of Gov.uk elements  & frontend toolkit might not be easy to import into project unless some modification on  gulp/grunt task runner are needed.

**Comment by hbweb** [comment]
This issue has been rectified 

In webpack.config file


```
sassLoader: {
          //includePaths: [path.resolve(__dirname, "node_modules/foundation-sites/scss")]
          includePaths: [
            path.resolve(__dirname, "node_modules/govuk_frontend_toolkit/stylesheets"),
            path.resolve(__dirname, "node_modules/govuk-elements-sass/public/sass"),
            path.resolve(__dirname, "src/style/govuk-template/stylesheets"),
          ]
        },
```

and in the main.scss file (for example)

```
$path: "/public/images/";
@import "govuk-elements";
@import "govuk-template";
```
