### ISSUE TITLE
Googly eyes on radios

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#354]
Cat certain browser zooms, the new radio styles have the select state off centre.

I suspect it may happen with the checkboxes too, but it's harder to notice there.

## How would you expect it to work?
The selected state should be in the centre of the radios.

## How does it work currently?
At 75% and 125% the selected state is off centre.

75% example:
![screen shot 2016-11-18 at 11 35 22](https://cloud.githubusercontent.com/assets/2204224/20429266/7c0c7aa0-ad85-11e6-8e51-ff632c1fb139.png)
125% example:
![screen shot 2016-11-18 at 11 35 09](https://cloud.githubusercontent.com/assets/2204224/20429277/839b5afc-ad85-11e6-8363-eb29bc1b9570.png)

## Explain the steps to reproduce the bug
Open elements in Chrome, set browser zoom to 75% or 125%

## Tell us about your environment
Googly eyes seen on Mac OSx 10.11.6, in Chrome 54, Firefox 49 and Safari 10

**Comment by robinwhittleton** [comment]
Chrome seems to be handling this better on Windows 10 at least now. No googly eyes at least, although there’s a single pixel white dot in the middle of the bullet at 75%.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
