### ISSUE TITLE
Swap inline checkbox example to new checkbox style

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#355]
The inline checkbox example in elements uses a native checkbox - we should probably change it to use the new checkbox style.

http://govuk-elements.herokuapp.com/form-elements/

## How would you expect it to work?
I think we used a native checkbox as the grey box style would have had too much visual weight. Now the new style has gotten rid of the box, we should be able to use the new checkbox style.

## Feel free to suggest a fix...
Swap check boxes example to new style

Screenshot of current:
![screen shot 2016-11-21 at 15 13 36](https://cloud.githubusercontent.com/assets/2204224/20487977/539b123c-affd-11e6-84cc-a39ba4695764.png)

**Comment by gemmaleigh** [comment]
Fixed by #394.
