### ISSUE TITLE
Add hover states back in for radios / checkboxes after iOS < 9.1 goes away

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_elements#357]
The new radios / checkboxes had [hover states](https://github.com/alphagov/govuk_elements/pull/296/commits/a844cd2a472b82e84306f7a2c4fc5a0990c01cbb#diff-05868dd1ba9cecec849b639448452f51R93) during their development and @edwardhorsford asked why it was removed. It had problems in iOS due to it’s ‘sticky’ hover behaviour showing ghost checkmarks after deselection. We managed to solve it using CSS4 hover media queries: https://github.com/alphagov/govuk_elements/pull/296/commits/e654d8bc721b0eba11bd11010600fa33da1dd077 . Unfortunately this was only Safari 9.1+, and we decided that the bad outweighed the good and removed it.

We should keep an eye on old iOS and add the hover behaviour back in again when Safari <9.1 mostly goes away.

**Comment by robinwhittleton** [comment]
The GOV.UK browsers and devices page currently recommends iOS Safari 9.3+; is this worth re-evaluating given the usability improvements for other browsers? I don’t have access to the stats to make the call, so would need to be discussed inside GDS.

**Comment by joelanman** [comment]
thanks robin! That sounds like the elements will fade out (opacity 0.15) when hovered - is that right? You got a screenshot anywhere?

**Comment by robinwhittleton** [comment]
Yep, it looked like this:
<img width="418" alt="screen shot 2017-10-27 at 10 59 56" src="https://user-images.githubusercontent.com/7414/32096235-22189ada-bb06-11e7-8376-74f3e76cf63e.png">
Checkboxes were similar; a 0.15 opacity checkbox while hovering.

**Comment by joelanman** [comment]
thanks! So thats when it isn't selected yet. Is there a change to a selected radio when hovered?

**Comment by robinwhittleton** [comment]
Not to the radio, no, as you can‘t deselect a radio. You can deselect a checkbox, but I’m not sure it would be useful to have a hover state there; the main point of the hover state is to give a hint of meaning to what could be just an empty box.

**Comment by edwardhorsford** [comment]
We could try it, but I'd be worried that a hover state on selected items might make them look unselected again. Eg: you pick something, move the mouse a little, and then it looks unselected. If we wanted a hover effect for that, we might want to look at something that doesn't apply it to the check itself but some other element (border or whatever).

**Comment by joelanman** [comment]
To clarify, I wasn't saying there should be one, I agree it could be confusing. Just wondering if it was being suggested, which it isn't.

**Comment by nickcolley** [comment]
See https://github.com/alphagov/govuk_elements/pull/570#issuecomment-419468197
