### ISSUE TITLE
Fix border colour on form controls

### ISSUE THREAD

**Issue by robinwhittleton** [alphagov/govuk_elements#358]
Borders of `.form-control`s are following the text colour, but that’s incorrectly defaulting to `#000`. Need to set `color: inherit;` for them so they correctly match the text colour.

**Comment by edwardhorsford** [comment]
Credit to @cfq for spotting this!

**Comment by selfthinker** [comment]
Doesn't `color` inherit automatically?

**Comment by gemmaleigh** [comment]
The user agent is setting  `color: initial`, rather than `color: inherit`.

`border: 3px solid;` sets `currentColor` for the border, and `currentColor` inherits from the user agent making it black (#000), rather than dark grey.
