### ISSUE TITLE
Radio focus style not applied on click in Firefox

### ISSUE THREAD

**Issue by gunjam** [alphagov/govuk_elements#361]
Clicking on radios in Firefox does not style with focus state, where it does for other inputs:
![ff-radios](https://cloud.githubusercontent.com/assets/142065/20563644/5c68a3fe-b181-11e6-972a-32574d835614.gif)

However tabbing through the form does apply focus style to the radios.

Tested in Firefox 50 and Firefox Developer Edition on macOS Sierra.

**Comment by robinwhittleton** [comment]
I investigated this in https://github.com/alphagov/govuk_frontend_toolkit/pull/358, but have decided in the end that tracking the default browser behaviour is preferable (especially seeing as eventually I’d like to remove the JS entirely).
