### ISSUE TITLE
Custom inputs have avoidable 300ms delay

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk_elements#362]
Issue found while visiting the Scottish Government's Device Lab

Inputs have a 300ms delay that can be avoided in some places.

https://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay

**Comment by robinwhittleton** [comment]
Reading @patrickhlauke’s documentation it looks like `touch-action: manipulation` might be a good thing to add to the radios and checkboxes.

**Comment by patrickhlauke** [comment]
make it so... ;)

**Comment by robinwhittleton** [comment]
Will be fixed by https://github.com/alphagov/govuk_elements/pull/363

**Comment by gemmaleigh** [comment]
Fixed by #363.
