### ISSUE TITLE
Missing pixels on the sides of unselected new radio buttons

### ISSUE THREAD

**Issue by willp-bl** [alphagov/govuk_elements#369]
Pixels appear to be missing on the sides of unselected new radio buttons, see https://github.com/alphagov/verify-frontend/pull/249#issuecomment-264417074

## Explain the steps to reproduce the bug
Run the verify-frontend containing the latest govuk_elements (in the above PR, look at README for instructions on how to run standalone)

## Tell us about your environment
* Version used: govuk_elements_rails (2.2.1)
* Browser Name and version: Chrome 54.0.2840.98 (64-bit) 
* Operating System and version (desktop or mobile): osx 10.11.6
* Link to your project: https://github.com/alphagov/verify-frontend/pull/249

**Comment by robinwhittleton** [comment]
Image from original report:

![oval_radios](https://cloud.githubusercontent.com/assets/7414/21018784/13a17056-bd66-11e6-81d9-5c397d66d37d.png)

I can’t replicate it using same Chrome and macOS versions – it looks round to me even when magnified to the same level. Might it be a Retina bug? I’m on a non-retina Macbook Air.

**Comment by willp-bl** [comment]
Screenshot is from a retina mac

**Comment by willp-bl** [comment]
I am going to close this as I am not seeing it now on the Verify frontend.  For some reason the checkboxes now look bigger (and rounder) than they did when I tested that PR.
