### ISSUE TITLE
JavaScript redirect can break

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#386]
https://govuk-elements.herokuapp.com/#test

this redirects to 

https://govuk-elements.herokuapp.comundefined/

```
Colin Rotherham [12:19 PM] 
Is it this file doing it?
http://govuk-elements.herokuapp.com/public/javascripts/redirect.js

[12:20]  
This line:
`if (newRoutes[fragment] !== 'undefined') {`

Should probably be:
`if (typeof newRoutes[fragment] !== 'undefined') {`
```

**Comment by colinrotherham** [comment]
Thanks @joelanman.

This line `if (newRoutes[fragment] !== 'undefined') {` assumes that a string `'undefined'`will be returned but that only happens if you use **typeof** to test `newRoutes[fragment]`.

Probably best to add a truthy check instead:
```js
if (newRoutes[fragment]) {
```

**Comment by colinrotherham** [comment]
It's being picked up in https://github.com/alphagov/govuk_elements/pull/387
