### ISSUE TITLE
No need for title attribute on cookie message.

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#388]
## How would you expect it to work?
It's an unnecessary title attribute because it is an exact match to the contents inside the link. So I would not expect it in this case.

## Feel free to suggest a fix...
Remove the title attribute.

## Explain the steps to reproduce the bug
https://govuk-elements.herokuapp.com

## Tell us about your environment
N/A

**Comment by robinwhittleton** [comment]
Fixed by https://github.com/alphagov/govuk_elements/pull/389
