### ISSUE TITLE
Lack of semicolons in details.polyfill.js broke us

### ISSUE THREAD

**Issue by maxwedwards** [alphagov/govuk_elements#396]
Upgraded our out of date Elements dependency for our service and our application broke with an 

>(intermediate value)(...) is not a function

exception.

After investigation it was because our concatenated `app.js` file which contained your `details.polyfill.js` file hadn't correctly handled the file.

We can fix this by adding a defensive semicolon to our IIFEs.

This issue is to let you know that removing semicolons really can trip other teams up. Is it really worth it in code that is intended to be consumed by other organisations?

**Comment by nickcolley** [comment]
Hey @maxwedwards !

Sorry about this issue, we're using [standard](http://standardjs.com/) to keep our codebase consistent without having to maintain (and bikeshed 😛 ) our own rule set.

While we'd recommend using build tools that anticipate valid JavaScript, I think we definitely can take some steps to add semi-colons when the assets are published!

There's some work going on into the new [GOV.UK Frontend](https://designnotes.blog.gov.uk/2016/10/14/introducing-gov-uk-frontend-alpha/), as part of this JavaScript module systems have been considered so I imagine this would be fairly trivial as part of a build process.

For pre-existing code it might be a tad more manual, so will leave this open so we can track this and make the code more defensive without breaking consistency.

Thanks for letting us know! 😄

**Comment by nickcolley** [comment]
In the meantime, some common ways you can make sure some common build tools concat JavaScript correctly:

- Grunt: https://github.com/gruntjs/grunt-contrib-concat#separator
```json
      options: {
        separator: ';\n'
      }
```
- Gulp: https://github.com/contra/gulp-concat
```js
.pipe(concat('main.js', {newLine: ';'}))
```

**Comment by maxwedwards** [comment]
Cheers for the Grunt / Gulp tips :)

I'll add that as well as defensive semicolons to our code base.

**Comment by nickcolley** [comment]
Following the launch of the GOV.UK Design System, GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

In GOV.UK Frontend we use a build system that prevents this issue from happening, thanks for raising this originally 😄
