### ISSUE TITLE
No need for ID or FOR attribute if input sits inside a label (implicit association)

### ISSUE THREAD

**Issue by trevorsaint** [alphagov/govuk_elements#398]
In the examples I am seeing both FOR and ID attributes in cases where the input sits inside the label. We have implicit association. 

Such cases include radio and checkboxes as shown here:
https://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons

We don't need these extra tags. It may be a good move to remove them and simplify the code even further.

## How would you expect it to work?
Just remove the FOR and ID attribute if the input sits inside a label.

**Comment by robinwhittleton** [comment]
Implicit association didn’t use to work in some old browsers / AT. Do we have any idea of where support became good enough to look at dropping this? Steve Faulkner [identified some issues with `<input type="text">` in various modern(ish) browsers](https://www.paciellogroup.com/blog/2011/07/html5-accessibility-chops-form-control-labeling/), but I’m not sure if this applies to radios/checkboxes too.

**Comment by trevorsaint** [comment]
@robinwhittleton Agreed in regards the use of the text input. In reference to checkboxes and radios I think support has always been fine with it. But will investigate obviously :).

**Comment by gemmaleigh** [comment]
The markup has been changed for radios and checkboxes:

```
<div class="multiple-choice">
    <input id="radio-inline-1" type="radio" name="radio-inline-group" value="Yes">
    <label for="radio-inline-1">Yes</label>
</div>
```

With the new markup, the input no longer sits inside the label - so the ID and FOR attributes are required.

Closing this issue.
