### ISSUE TITLE
Tables have inconsistent font sizes

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#402]
The tables in elements use two different font sizes - normally 19px for text, but 16px for tabular numbers.

![screen shot 2017-02-08 at 17 36 43](https://cloud.githubusercontent.com/assets/2204224/22749430/35e25e42-ee25-11e6-96a5-b29ff2707f77.png)

## How would you expect it to work?
The font size should be consistent across the table.

## How does it work currently?
Setting tabular numbers for numeric data sets font size as a byproduct - this is currently 16px.

## Feel free to suggest a fix...
Make it possible to set tabular numbers without setting a font size.

## Explain the steps to reproduce the bug
Look at the tables on [this page](http://govuk-elements.herokuapp.com/data/#numeric-tabular-data).

**Comment by gemmaleigh** [comment]
It looks like the .numeric class is also setting a font-size, as it is using the core-font mixin from the frontend toolkit.

A quick fix would be to change this to core-19, but ideally we'd like a way to use nta-tabular without having to set a font size.

A better solution would be to have a generic .numeric class, to be used for aligning numbers that only changes the font-family to nta-tabular.

**Comment by gemmaleigh** [comment]
This was fixed in GOV.UK elements v3.0.1 (PR #424 fixed this).
