### ISSUE TITLE
List items are hard to differentiate when wrapping over 2 lines

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk_elements#407]
When an item in a list is long enough to wrap over two lines and doesn't contain any list styling (e.g. bullets or numbers)  it can be hard to scan as the wrapped line could be mistaken for a new list item.

#### How would you expect it to work?
I would expect the spacing between `.list` `li`'s to be larger so there is more visual separation between items.

#### How does it work currently?
Currently they are 5px

<img width="255" alt="wrapped-lists" src="https://cloud.githubusercontent.com/assets/23356842/23122196/1fcc9430-f75b-11e6-9780-984bbf695e21.png">

#### Feel free to suggest a fix...
10px looks good to me, thoughts?

**Comment by edwardhorsford** [comment]
Could you also indent the subsequent lines?

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
