### ISSUE TITLE
All the example links are broken

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_elements#416]
For example the 'Typography' link at the bottom of [this page](http://govuk-elements.herokuapp.com/typography/).

It looks like we moved all the examples into an 'examples' folder but didn't update the links. Weirdly though, when I go to the [URL I'd expect to work](http://govuk-elements.herokuapp.com/examples/example_typography.html) I still get an error.

**Comment by gemmaleigh** [comment]
It looks like #411 caused this. When I run the site locally, I get this error:

Template render error: (govuk_elements/app/views/examples/example_grid_layout.html)
 Error: template not found: includes/service_manual_navigation.html.

I'll update these pages to use the new navigation include.

**Comment by 36degrees** [comment]
Oh!! Sorry! Not sure how I managed that.

**Comment by gemmaleigh** [comment]
No worries, I didn't spot it either... opening a PR to fix!
