### ISSUE TITLE
Idea: make conditional content line up with label content

### ISSUE THREAD

**Issue by kateiw** [alphagov/govuk_elements#422]
Hey, I've had an idea based on playing around with conditional content on radio buttons.

With conditional content drop downs, the text doesn't align with the content in the label above, which looks a bit weird and makes it harder to read.

Before:

![screen_shot_2017-03-16_at_17 55 44](https://cloud.githubusercontent.com/assets/20725026/24011389/8f9571fe-0a72-11e7-9055-79d5d4760379.png)

What we've been playing around with:
![screen shot 2017-03-16 at 18 03 12](https://cloud.githubusercontent.com/assets/20725026/24011489/dc8741c2-0a72-11e7-9ed6-9317b3c1a395.png)

**Comment by joelanman** [comment]
Looks nice, what part is conditional in this example? Just the continue button?

**Comment by kateiw** [comment]
Ignore the button for now... that's also another new thing we've invented apparently!

But this particular idea is about bringing the text in the drop down inline with the text above, and then shifting the grey line across to sit aligned to the middle of the radio.

**Comment by joelanman** [comment]
![conditional](https://cloud.githubusercontent.com/assets/1132904/24042763/5376fd5c-0b0b-11e7-8fcb-a6d927f61bd5.gif)

**Comment by edwardhorsford** [comment]
I like the idea of content lining up with the labels - it feels and looks neater.

I'm less sure about moving the border, but can see that if you don't, you get a big bit of white space.

In *most* cases conditional content is the child of a radio or checkbox - but we also use inset for child content of the details element. Would we also inset these?

![screen shot 2017-03-17 at 13 26 59](https://cloud.githubusercontent.com/assets/2204224/24045004/8b777bf0-0b15-11e7-9329-24a854f80a8c.png)

**Comment by gemmaleigh** [comment]
Thanks for raising this @kateiw!

I'm trying to close some of the govuk-elements issues, what's the verdict on this one - would we like to move the left grey border when we reveal extra content - using radio buttons or checkboxes?

I'm happy to make that change if there's consensus.

**Comment by edwardhorsford** [comment]
It would be good to see this in other use cases.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

This has however been implemented in the Design System for conditional reveals in both the [checkboxes](https://design-system.service.gov.uk/components/checkboxes/) and [radios](https://design-system.service.gov.uk/components/radios/) components:

![design-system service gov uk_components_radios_conditional-reveal_index html](https://user-images.githubusercontent.com/121939/44471569-166bd800-a624-11e8-9a5d-bc66f163c9f0.png)

Thanks, @kateiw! 🎉
