### ISSUE TITLE
A gem wrapper around govuk_elements

### ISSUE THREAD

**Issue by robmckinnon** [alphagov/govuk_elements#44]
For ease of using `govuk_elements` in Ruby on Rails apps, could you create a `govuk_elements_gem`?

This approach would be consistent with the gem wrapper around the `govuk_frontend_toolkit`: https://github.com/alphagov/govuk_frontend_toolkit_gem

**Comment by gemmaleigh** [comment]
Closing as [you've done this](https://rubygems.org/gems/govuk_elements_rails).
