### ISSUE TITLE
css in not namespaced across our repos

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/govuk_elements#470]
Currently we live in a world where we have multiple patterns, and may wish to in the future do this.
our sass and css imports are not namespaced, so due to rails asset pipeline magic, its hard to trace where things are coming from. i believe namespacing would help this. 

so instead of `@import typography` it would help if it was `govuk_elements/typography`

https://github.com/alphagov/govuk_frontend_toolkit/issues/415

**Comment by gemmaleigh** [comment]
The elements typography file is already called `_elements-typography.scss, to separate it from the `typography.scss` file from the frontend toolkit.

Yes this would be useful and it's something we are looking to introduce in GOV.UK frontend. 

https://github.com/alphagov/govuk-frontend/blob/master/docs/coding-standards/css.md#namespace

I'm a concerned about making breaking changes like this to GOV.UK elements in the meantime.

**Comment by nickcolley** [comment]
@gemmaleigh if we raise this as an issue over at govuk-frontend we can close it here?

**Comment by gemmaleigh** [comment]
@nickcolley I don't mind if you leave it open here, it is an issue with the existing code - it's probably not going to be something that gets fixed here though. 

Feel free to raise an issue over on the govuk-frontend repo and when we start adding namespaced code to the repo, I'll close it then.

**Comment by gemmaleigh** [comment]
I'm going to close this, as the intention is to replace govuk-elements-sass with govuk-frontend. We have coding guidelines and those include our use of namespaces. 

https://github.com/alphagov/govuk-frontend/blob/master/docs/coding-standards/css.md#namespace
