### ISSUE TITLE
Focus styles interfere with underlines when links span multiple lines.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#471]
Our focus style for links is a solid background colour. For some font sizes (larger ones?), when the link wraps to multiple lines, the focus style obscures part of the underline.

Live [example](https://www.gov.uk/government/publications/there-has-never-been-a-better-time-to-export-overseas) from GOV.UK:
![screen shot 2017-05-19 at 13 10 07](https://cloud.githubusercontent.com/assets/2204224/26247338/57912ed8-3c95-11e7-9ddc-58f2c4faaab3.PNG)

In this example, the underline is clipped in the top line, and the underscore is entirely obscured, making it look like two links.

#### How would you expect it to work?
Focus styles should not obscure content. Plausibly the underline isn't _so_ important, but other things like underscores are obscured too.

#### How does it work currently?
For some font size combinations, part of the underline is obscured if the link wraps to multiple lines and has focus.

#### Feel free to suggest a fix...
Increase line height? Different focus style? dunno!

#### Explain the steps to reproduce the bug
1. Visit [this page](https://www.gov.uk/government/publications/there-has-never-been-a-better-time-to-export-overseas).
2. Find a link that wraps to multiple lines and is larger than 19px
3. Profit

#### Tell us about your environment
* Tested on Chrome 58.03 on OSx

**Comment by igloosi** [comment]
remove `text-decoration` style on `a:focus` ? visually the link is visibly focus with yellow background

**Comment by edwardhorsford** [comment]
Looks like this:
![screen shot 2017-05-19 at 13 35 43](https://cloud.githubusercontent.com/assets/2204224/26247949/1d50e198-3c98-11e7-8258-fe4a8397c58e.PNG)

Not sure about it, and the underscore is still hidden.

**Comment by igloosi** [comment]
the name is messed up "572230_Exporting is GREAT (ENGLISH)_Low res" random underscores missing. clipping of g is an issue though. increasing line height fixes that

**Comment by gemmaleigh** [comment]
Hi @edwardhorsford, thanks but this issue needs to be raised over on the govuk_template repo.

https://github.com/alphagov/govuk_template/blob/master/source/assets/stylesheets/_accessibility.scss#L58

**Comment by gemmaleigh** [comment]
Also any issues with the appearance of govspeak content should be raised on static: https://github.com/alphagov/static/

**Comment by edwardhorsford** [comment]
@gemmaleigh does this depend on what we consider the issue / fix?

A fix may be related to line hight - in which case wouldn't it be frontend-toolkit font mixins?

**Comment by alextea** [comment]
www.gov.uk doesn't use elements type styles, so this isn't relevant here.

**Comment by gemmaleigh** [comment]
Closing here. 

If it's a line-height fix, then yes - it would be the [govuk_frontend_toolkit's typography mixins you will need to amend](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss).
