### ISSUE TITLE
Disabled radios and checkboxes have the wrong cursor

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#517]
When the disabled attribute is on an element, we grey it out. However, the pointing hand cursor remains - it shouldn't as the element isn't actionable.

#### How would you expect it to work?
I'd expect to see the pointer cursor.

Example:
![radio-disabled-cursor](https://user-images.githubusercontent.com/2204224/28011959-1f0c7cf8-655c-11e7-9a9c-eb61f862b612.gif)

**Comment by robinwhittleton** [comment]
Could go with `cursor: not-allowed` but `cursor: default` is probably the best option…
