### ISSUE TITLE
TODO: add example for email address

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#535]
It was asked recently on Slack why we weren't recommending using `type=email` for email. I don't think we recommend against it, but just haven't got a suitable example for it.

#### Suggestion
Lets add a section for email addresses.

Suggest it:
* Uses `type=email`
* Disables browser validation.
* Default length longer than normal.

We've also got an example that shows how users can use progressive disclosure to enter an email address. We should update that example with the above.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

For reference, there is now [guidance on asking users for email addresses in the Design System](https://design-system.service.gov.uk/patterns/email-addresses/).
