### ISSUE TITLE
Request:  Pagination

### ISSUE THREAD

**Issue by GuruTom** [alphagov/govuk_elements#538]
Hi All,

While creating an In house application for The Insolvency Service we need to implement some sort of pagination for the user so we can limit the number of cases per page. Style wise, our first thought was to check this repository to see if there are any that have been created by GDS.

Currently, we have created our own style but thought it could be something you could add for use by other departments so that it's consistent across the board

We have currently created this:

![dcrs-pagination](https://user-images.githubusercontent.com/3950254/28864350-2cac402c-7764-11e7-9707-8bdd5d385398.png)

Thanks 
Tom

**Comment by dashouse** [comment]
Hey @GuruTom, thanks for this. 

There are a couple of projects underway that are both documenting existing components and creating new ones. There is an existing pagination component (<-- Prev    Next--->) style but not (as far as I'm aware) one that shows the user how many pages are available / allows users to move through the pagination in a non linear order.

We are also working on a more formal method to contribute components and patterns so it would be great to talk to you about this in more detail.

**Comment by GuruTom** [comment]
HI @dashouse, thanks for your response.

That's great news have you got an email I can contact you on?

**Comment by dashouse** [comment]
@GuruTom Sure, it's david.house@digital.cabinet-office.gov.uk

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

I've recorded this issue in [the backlog issue for pagination](https://github.com/alphagov/govuk-design-system-backlog/issues/77).
