### ISSUE TITLE
Back link wrong colour when focused

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#540]
The back link changes to our standard govuk-blue when focused - I presume it should stay black.

Screenshot:
![screen shot 2017-08-07 at 11 13 37](https://user-images.githubusercontent.com/2204224/29022528-9b4815fa-7b61-11e7-8abc-00696c3e39db.png)

**Comment by igloosi** [comment]
seem that all of our links when focused maintain their default gov.uk colour
```
a:link:focus {
    color: #005798;
}
```
and there is no exception for back link. if the consensus is to keep in black on focus that we can add it in.

**Comment by nickcolley** [comment]
If you remove the `border` property's references to the black, it'll pick up the `currentColor` and end up looking like:

![screen shot 2017-08-08 at 11 00 22](https://user-images.githubusercontent.com/2445413/29066983-ddfc83c8-7c28-11e7-8627-7f4e56c77214.png)

**Comment by edwardhorsford** [comment]
I suspect this regression was introduced by this pr: https://github.com/alphagov/govuk_template/pull/272

I think it should stay black. The reason we added the different blue focus colour was so that the contrast met our standards - this isn't a problem with the black links.

**Comment by igloosi** [comment]
got to love the generic a:link:focus ...

**Comment by igloosi** [comment]
so, the _accessibility.scss in govuk_template is overriding this. we either fix it there or stick an !important (i wouldn't to) here

**Comment by gemmaleigh** [comment]
This was fixed by #544.
