### ISSUE TITLE
Example markup for errors and validation out of date

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#541]
The example markup on the errors and validation page still has separate headings and legends - which was changed in #507

**Comment by igloosi** [comment]
@selfthinker could you update the [page](https://govuk-elements.herokuapp.com/errors/) with the code change in your PR?

**Comment by edwardhorsford** [comment]
I think this may be a mistake on my part.

The example which I thought was a single question isn't our standard format - as it has a heading, some text, and then the legend.

The example is probably correct, but we're missing an example of a page-per-thing validation pattern which is likely the *most* common page. I'll raise an issue for that instead.
