### ISSUE TITLE
Add an example of a question page with a lot of content

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk_elements#542]
Raising in Elements, but might be better somewhere else.

Was recently talking with Jen Lambourne about a page with a fair amount of content - and how it should look / be marked up. With our current examples and page per thing we'd likely end up with pages where the question is a large distance from the input it's related to.

In this case, it's probably better to have a more generic h1, paragraph, and _then_ the question.

An example from Passports:
![42 compare your old and new photos renew your passport gov uk](https://user-images.githubusercontent.com/2204224/29026072-da682fc6-7b71-11e7-9124-98a8b8d30b2d.png)

Would be good for us to explore markup to correctly associate the description with the question.

**Comment by edwardhorsford** [comment]
I've realised that the `Form validation - single question` is _almost_ what I want. 

Suggest changing that to be an example for more content, and then making another single question example which has no content (raised as #543 )

**Comment by selfthinker** [comment]
I agree that it would be good to write more (and better) text for the "single question" example. Mostly because the additional text is not necessary. It could easily be changed to make h1 and legend the same. ("Are your personal details correct and up-to-date?" as h1/legend with no intro.)
The new page with more content should make clear from the context that that content is necessary to have on the page.

**Comment by edwardhorsford** [comment]
A couple examples from passports with additional guidance:
![screen shot 2017-10-10 at 15 10 50](https://user-images.githubusercontent.com/2204224/31391121-8eb3ecbc-adcd-11e7-839e-43bdde4afa54.png)
![screen shot 2017-10-10 at 15 10 04](https://user-images.githubusercontent.com/2204224/31391122-8ee60634-adcd-11e7-9482-c56d76c79491.png)
![screen shot 2017-10-10 at 15 07 35](https://user-images.githubusercontent.com/2204224/31391123-8f270f58-adcd-11e7-8237-774705ab062f.png)

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
