### ISSUE TITLE
Move 'Check your answers' Sass from Prototype Kit into Elements

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_elements#550]
Now this code has been thoroughly built for accessibility by @selfthinker we should move it to Elements so that it can be more easily used in production environments.

**Comment by edwardhorsford** [comment]
In addition it would be good for the html and screenshot to appear _somewhere_ in the Elements website.

I might suggest creating a new section 'page patterns' which can have Check your answers and the confirmation page pattern (and more as we make them).

I'm not sure alpha and beta patterns are deserving of a page of their own, but I don't know where else they might go. Perhaps a page on 'smaller patterns'?

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

The ['check your answers' pattern is in the Design System](https://design-system.service.gov.uk/patterns/check-answers/), but currently does not have code that users can use in their service. This is something we're looking to address soon.
