### ISSUE TITLE
Date form example uses invalid HTML

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govuk_elements#551]
The [date form example](https://govuk-elements.herokuapp.com/form-elements/example-date/) uses invalid HTML. The [W3C Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgovuk-elements.herokuapp.com%2Fform-elements%2Fexample-date%2F) says:

> Attribute `pattern` is only allowed when the input type is `email`, `password`, `search`, `tel`, `text`, or `url`.

It was added in #47, and I believe it was done to make sure the number keyboard shows up in some devices -- at least at the time.

We should find out if it's still necessary, and if it is, we should add some kind of documentation somewhere that the invalid HTML is intentional.

**Comment by edwardhorsford** [comment]
The `pattern` attribute forces numeric keypads on iOS devices. Having just tried it, `type=number` alone does not force the numeric keypad.

For other types of numbers, `type=number` isn't appropriate and `type=text` should be used. For dates it's probably fine though.

Agree should probably add some documentation.

@hannalaakso anything to add?

**Comment by hannalaakso** [comment]
Here's a blog post about the different iOS keypads when you add or omit the pattern attribute on number inputs: http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms We are looking to create guidance on choosing the most appropriate input and pattern for different use cases involving numbers.

Agree that adding a note about the invalid HTML is a good idea.
