### ISSUE TITLE
Should our colour naming be simpler and unopinionated?

### ISSUE THREAD

**Issue by charlesrt** [alphagov/govuk_elements#561]
Some of our colour naming could be considered opinionated. For example, baby pink.
Some of our colour naming is complex. For example, Fuschia is misspelt (should be Fuchsia). 

A suggestion for simpler and unopinionated colour naming:
<img width="970" alt="screen shot 2017-10-02 at 15 46 15" src="https://user-images.githubusercontent.com/13832188/31083403-825b3ba4-a789-11e7-9e4f-182baa6b8d30.png"> 

**How would you expect it to work?**
I started a pull request #560 but made a mistake as to how the Sass variables were generated (imported from Frontend Toolkit).
If we agree that a change should be made, I think the only change on Elements would be a content one to reflect the new naming as the main change should take place in `_palette.scss` in the Frontend Toolkit.

The change doesn't need to be a breaking one. Existing Sass variables can and should continue to be supported. 

For example, `$fuschia` could still be maintained in addition to a correctly spelled version and a simpler named version:

```
$fuschia: #912b88;
$fuschia-50: #c994c3;
$fuschia-25: #e9d4e6;
$fuchsia: $fuschia;
$fuchsia-50: $fuschia-50;
$fuchsia-25: $fuschia-25;
$bright-purple: $fuschia;
$bright-purple-50: $fuschia-50;
$bright-purple-25: $fuschia-25;
```

I can raise new pull requests in Elements and Frontend Toolkit if we reckon this is a good idea.

**Comment by 36degrees** [comment]
I think this is a good change to make.

My gut feeling is that we should just make these changes in GOV.UK Frontend before its release, and leave the palette in Frontend Toolkit / Elements as is.

This means we would have to put up with the spelling mistake and opinionated naming for a little bit longer (until Frontend is released), but as we've coped with them for five years already I'm just not convinced it warrants a breaking change here.

Thoughts?

**Comment by 36degrees** [comment]
(Also, I like bright purple as an alternative name 👍)

**Comment by nickcolley** [comment]
This is a good illustration of how having two tiers of can help reducing breaking changes.

For example:
```scss
$error: $red;
```

When we use variables that are directly connected to how they look rather than how they're used it's hard to change them without them being odd.

For example if you want to make something red blue since we've decided that our errors states should be blue you can end up in a position where you're doing something like `$red: blue`

**Comment by nickcolley** [comment]
That said I see no reason why we could not deprecate these as described above, so long as they have the old variables still pointing to the new ones.

e.g. `$baby-pink: $light-pink`

**Comment by edwardhorsford** [comment]
I'm rather curious if these colours actually get used - the majority of services shouldn't have a very wide colour range.

@nickcolley I think we've already got several semantic names - but should have more - `govuk-blue` being a good example. It wouldn't surprise me if services are using these colours correctly too though - I might expect in some services we might find:
`$alert-warning: $baby-pink`

**Comment by 36degrees** [comment]
The naming of colours in GOV.UK Design System (and GOV.UK Frontend) is a lot less opinionated, as suggested in this issue:

  - `mauve` → `light-purple`
  - `fuchsia` → `bright-purple`
  - `baby-pink` → `light-pink`
  - `mellow-red` → `bright-red`
  - `grass-green` → `light-green`

Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches - therefore this isn't something we'd be looking to 'backport', so I'm going to close this.
