### ISSUE TITLE
Possible accessibility issue with high contrast mode on Edge

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk_elements#569]
A team in NHS have reported some users struggling with our buttons in high contrast mode on Windows. They believe that they were using an Edge browser. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1590604/32052130-2a25e9b0-ba4f-11e7-89f4-800ddb012133.png)

As you can see the radios have big white borders, but the button background doesn't seem to have changed colour.

**Comment by robinwhittleton** [comment]
What would the expected behaviour be? White background and black text, or no border?

**Comment by timpaul** [comment]
For the radios I'd suggest no border. For the Next button - reverse video?

(Also, there's a chance they're using an old version of Elements...)

**Comment by robinwhittleton** [comment]
There was a problem with Win10 high contrast mode with old pre-release radios, but that screenshot is showing the fixed version. I don’t remember the outlines but I wouldn’t say for certain they weren’t there.

**Comment by robinwhittleton** [comment]
Just tested on Elements and am not seeing the problem with radio buttons in the photo. Is there a link to the site they were testing on nhs.uk?

**Comment by selfthinker** [comment]
By the way, you can see in the screenshot that is **is** Edge. (But it would be impossible to find out what tool they used, except that it changed the colours of the whole desktop, not just the browser, so at least cannot be browser settings.)

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so given that we've not been able to reproduce this I'm going to close this.
