### ISSUE TITLE
Standardise the form elements code snippets

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#571]
The [form elements snippets](https://govuk-elements.herokuapp.com/form-elements/) currently differ from each other - for example some are wrapped with `<div class= "form-group">`, some have `<form>` tags, some have neither.

This makes training a bit tricky as we have to tell people to wrap some snippets, or delete form tags from other snippets.

It may not be possible to make them all the same, as some snippets are simple elements, others are more complex with grouping. But for example, I think we can probably remove `<form>` from all of them.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
