### ISSUE TITLE
Details polyfill often not necessary

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govuk_elements#572]
We currently polyfill most features of our [details/summary element](http://govuk-elements.herokuapp.com/typography/#typography-hidden-text) ("progressive disclosure"). But most modern browsers support it nowadays and according to [HTML5 Accessibility](http://www.html5accessibility.com/) even its accessibility is 100% supported in Chrome, Firefox and Safari.
It's only IE, Edge and older browsers which need some special treatment. It would make sense to only use the polyfill for those browsers and use the native version for those which fully support it.

## Cons

Changing the polyfill that way would need a lot of testing.
And there will be an intersection of older browsers which support the element but aren't accessible yet. Those will get a worse experience than before, but then again, the amount of users using old Firefoxes, Chromes and Safaris should be extremely small.

## Pros

Doing this would reduce complexity of the polyfill.
And it would fix things which work better natively than with our polyfill (e.g. in VoiceOver on iOS).

I guess it would probably not make sense to change this for the sake of it, but rather when touching the code anyway or if there is a specific problem which would better be fixed by this than complicating it further.

**Comment by nickcolley** [comment]
This seems like a good idea, we seem to be polyfilling sections already.

https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/details.polyfill.js#L15

Our check looks to be brittled based on https://github.com/Modernizr/Modernizr/blob/master/feature-detects/elem/details.js

👍

**Comment by timpaul** [comment]
Do we think the development of GOV.UK Frontend is a good opportunity to revisit this code and make the polyfill more targeted?

**Comment by nickcolley** [comment]
I've raised an issue on GOV.UK Frontend to explore reducing the scope of polyfilling which I hope will address these issues, thanks again Anika.

See https://github.com/alphagov/govuk_elements/issues/573#issuecomment-419465180
