### ISSUE TITLE
Radios with headings inside labels are misaligned

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk_elements#581]
Pointed out by gordonmcmullan_hmrc this example from Elements is misaligned

<img width="697" alt="screen shot 2017-12-07 at 16 06 45" src="https://user-images.githubusercontent.com/23356842/33726333-9fc317fe-db6c-11e7-85fc-13d067790028.png">

I believe this was affected by this PR (https://github.com/alphagov/govuk_elements/blob/8f88ccc46f7e71d2c8f4a56f4bac4beda1126cd5/assets/sass/elements/_elements-typography.scss) to add `display: block` to headings. It looks like that the margins we're previously collapsing, but with `display: block;` they are not.

**Without `display: block;`**
<img width="623" alt="screen shot 2017-12-07 at 16 39 19" src="https://user-images.githubusercontent.com/23356842/33726542-3e1ed5dc-db6d-11e7-84c9-8eb78b37550d.png">

Would suggest contextually adjusting the heading classes within the labels rather than removing the `display: block;`

**Comment by igloosi** [comment]
and also removing that br

**Comment by selfthinker** [comment]
Or keep the `<br>` and change the class of the span from `heading-small` to `bold-small`. That also makes more sense as it's not a heading.

**Comment by selfthinker** [comment]
I fixed it in #591.
