### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by Nooshu** [alphagov/govuk_elements#582]
We can currently use two urls to get to elements. I believe Search engines are intelligent enough to know the difference so there shouldn't be an SEO impact, but if it is a simple fix then it would be worth making it.
- https://govuk-elements.herokuapp.com/
- http://govuk-elements.herokuapp.com/

#### How would you expect it to work?
I would expect HTTP to redirect to HTTPS.

#### Feel free to suggest a fix...
There is an express module available that we may be able to use that can help us do this. More details about it [here](https://www.npmjs.com/package/heroku-ssl-redirect)

**Comment by joelanman** [comment]
This was done and then reverted a while ago, not sure why https://github.com/alphagov/govuk_elements/pull/501

**Comment by Nooshu** [comment]
Original changes in #480. Looks to be using a different method than listed in the [heroku-ssl-redirect](https://www.npmjs.com/package/heroku-ssl-redirect). @igloosi do you happen to know what broke when this was deployed?

**Comment by joelanman** [comment]
Might be reading it wrong since I'm on mobile but looks like a possible bug in the original pr:

var utils = path.join(__dirname, '/lib/utils.js')

I think this needs a 'require', like the similar lines above it

**Comment by Nooshu** [comment]
Well spotted @joelanman, certainly worth investigating. Or try the module listed if that is easier?

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.
