### ISSUE TITLE
Request: avoid coupling styling to `#content`

### ISSUE THREAD

**Issue by lennym** [alphagov/govuk_elements#585]
#### How would you expect it to work?

Since the govuk template includes a "skip to content" link which points to `#content` it is desirable that this id can be placed on the most relevant element.

In particular, because we use a phase banner, we wish to point the `#content` anchor to after the phase banner, which needs to be inside a container with the relevant styles.

#### How does it work currently?

Because styling is applied to `#content` we cannot place this id at the most appropriate position in the page for users to access without having to write additional CSS to remove the styles which have been added.

It's possibly worth noting that the documentation for this library contains a workaround for this exact issue - https://github.com/alphagov/govuk_elements/blob/master/assets/sass/elements-documentation.scss#L27-L32

#### Feel free to suggest a fix...

As pointed out in the comments for the code linked above, this probably isn't possible without a major version change for elements, but I'd recommend using a selector that is not bound to accessibility functionality to apply these styles.

**Comment by quis** [comment]
Related issue: https://github.com/alphagov/govuk_template/issues/271

**Comment by joelanman** [comment]
thanks @lennym - in the new GOV.UK Frontend Alpha, designed to replace Elements, we are decoupling this style from the #content Id

**Comment by lennym** [comment]
Thanks. I'll keep an eye on that repo...

**Comment by edwardhorsford** [comment]
Is this a 'wont fix' for elements?

If it's an easy fix can it be added to elements?

**Comment by nickcolley** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

In [GOV.UK Frontend](https://github.com/alphagov/govuk-frontend) we have avoided coupling styling to the main element with an id, instead using a class for the user to append to the element.

Thank you for raising this :)
