### ISSUE TITLE
Field ordering in date field example

### ISSUE THREAD

**Issue by djrobstep** [alphagov/govuk_elements#592]
The elements guide shows example date fields in [dd] [mm] [yyyy] order.

I'd be interested to know what the rationale is for presenting in the fields in this order, as opposed to the less ambiguous [yyyy] [mm] [dd] order.

While less familiar for some at first glance, the year-first ordering has many compelling advantages:

- More familiar for people from other cultures and countries (year-first is used in China, Japan, and many other countries)
- Avoids confusion with US-style ordering (dd-mm-yy and mm-dd-yy are both common and thus easily confused, but nobody uses yyyy-dd-mm).
- yyyy-mm-dd is inherently more intuitive as the ordering is consistent with the larger-field-first ordering that we're used to for numbers generally
- More internationalist and in line with ISO8601

The GDS tech blog today notes the confusion and ambiguity of year-last ordering:

https://gdstechnology.blog.gov.uk/2018/01/31/its-time-to-use-iso-8601-across-government/

So is it wise to use it for user inputs?

I wonder if there been any cross-cultural user research on this to see which is better?

**Comment by cjforms** [comment]
As you noted, year-first ordering works well for technologically-minded people and in technical contexts.

The majority audience for UK government services is ordinary people with no technological background, and we observe that nearly all of them quote dates starting with the day of the month. This is especially true for memorable dates such as their date of birth. 

A key feature of government forms design is 'Design for common scenarios first' (https://www.gov.uk/service-manual/design/form-structure), and we have seen in user research that the day-first method works well for the majority of our users.

**Comment by djrobstep** [comment]
> As you noted, year-first ordering works well for technologically-minded people and in technical contexts.

? I didn't mention the needs of technologically-minded people or technical contexts at all.

The main issue is cultural inclusion and the experience of people from other countries and cultures. [At least 20% of the world population is used to writing dates year-first](https://en.wikipedia.org/wiki/Date_format_by_country). 

Many people are users of a mix of both US and non-US websites and other media, and are thus exposed to a mix of day-first and month-first date inputs and displays. Year-first reduces the ambiguity and uncertainty for users in this category also.

The [gov.uk design guidance says to design "for everyone"](https://www.gov.uk/guidance/government-design-principles#this-is-for-everyone). Catering for merely the majority is often marginalizing to minorities.

Is a form field that prioritizes the experience of white native-born people at the expense of many minorities, immigrants, and foreign users the way to do that? Particularly for sites and services that have an overseas audience?

This is similar to the situation with name fields. While first name/last name probably works OK for the majority (aka native-born white people), a single field is preferred because it's more culturally inclusive.

Absent definitive cross-cultural user research comparing the options, surely the more inclusive, more internationally friendly, less marginalizing, and less ambiguous ordering ought to be preferred?

**Comment by timpaul** [comment]
You're right that we say 'design for everyone', but we also say [design for the most common scenarios first](https://www.gov.uk/service-manual/design/form-structure#design-for-the-most-common-scenarios-first).

Before considering year-first date ordering we'd need to establish the impact on people who are used to day-first ordering, and then make a judgement based on the relative impact and size of those two groups.

I'm not aware that this work has been done but I'd love to see it.

**Comment by joelanman** [comment]
@djrobstep to answer your original question, our day-first pattern has been tested with many users over many services. Most services get about 6 participants every couple of weeks, for a few months. This has included people from different cultures. It works well, and we have not seen any common or strong enough issues to make a change away from the format. As @cjforms points out, it's the way the majority of our users think about dates, a change would make it less intuitive for them.

**Comment by selfthinker** [comment]
Can you please clarify which example date you are referring to? Do you mean https://govuk-elements.herokuapp.com/form-elements/example-date/?

As every field on there is labelled appropriately, I wonder why anyone would confuse them?
I mean, I understand that people often don't read and might not notice the labels or the hint. But lots probably do, especially those which are used to a different culture and date formats.

Maybe a good way to make sure people have added a date correctly is by displaying it back to them in "12 June 1970" format (and not "12 6 1970" format), either on the same page or at least on the last "check your answers" page before they submit the whole thing.

**Comment by edwardhorsford** [comment]
@selfthinker Displaying an entered date as `12 June 1970` is exactly what we'd normally do on Check your answers pages.
