### ISSUE TITLE
Links to DesignPattern Hackpad are broken

### ISSUE THREAD

**Issue by selfthinker** [alphagov/govuk_elements#594]
There are currently 11 links to the old [DesignPattern Hackpad](https://designpatterns.hackpad.com/) which are now broken because they don't redirect correctly to the new [Dropbox Paper](https://paper.dropbox.com/doc/GOV.UK-Design-Patterns-Wiki-hkou7bpzKya8Dadv24V1z).

I tried to fix it quickly but the content has diverged so much that there are no 1:1 equivalents anymore. (I couldn't find anything about "colour" or conditional form fields, radio buttons and checkboxes are now two different pages, etc.)

**Comment by timpaul** [comment]
Thanks for this. I've gone through the content and tried to suggest appropriate pages in Dropbox Paper for each Hackpad link. The only one I couldn't find something for was colour. Radios and checkboxes has 2 pages on Dropbox so we would need to tweak the content to link to both these.

## Colour
- http://govuk-elements.herokuapp.com/colour/
- no equivalent. Remove for now.

## Tables
- http://govuk-elements.herokuapp.com/data/
- Link to https://paper.dropbox.com/doc/uJx87vr8kI2xKiLwsEdRt

## Buttons
- http://govuk-elements.herokuapp.com/buttons/
- Link to https://paper.dropbox.com/doc/ghLqL5a9Ostxxb3rvBhyO

## Form fields
- http://govuk-elements.herokuapp.com/form-elements/
- link to https://paper.dropbox.com/doc/8NLlgz9tjR8OzTz2N9wE3

## Select boxes
- http://govuk-elements.herokuapp.com/form-elements/
- https://paper.dropbox.com/doc/v7PWDvPDV2tmc9pzDbm3s

## Radio buttons and  checkboxes
- http://govuk-elements.herokuapp.com/form-elements/
- Link to https://paper.dropbox.com/doc/oIwWoxwBKClt5IXvDbnpF
- Link to https://paper.dropbox.com/doc/HDLVh9YAhInay2xJ7vBl8

## Conditional form fields
- http://govuk-elements.herokuapp.com/form-elements/
- Link to https://paper.dropbox.com/doc/rUra4ZisgaWjafhBP1ivr

## Error messages and validation
- http://govuk-elements.herokuapp.com/errors/
- Link to https://paper.dropbox.com/doc/Error-messages-fifEJpOYMGjRy0lHTmthb

## Alpha and beta banners
- http://govuk-elements.herokuapp.com/alpha-beta-banners/
- link to https://paper.dropbox.com/doc/yhMGdJd3rigZpuSEHR1k0

**Comment by selfthinker** [comment]
Thanks!
I actually miscounted, there are 10, not 11 occurrences of Hackpad URLs in Elements. But the 10th is in an [include that isn't used anywhere](https://github.com/alphagov/govuk_elements/blob/master/app/views/includes/phase_banner.html), so you got all 9 of the relevant occurrences.
