### ISSUE TITLE
Max year in date examples is 2016

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk_elements#597]
The year inputs in [the date examples](http://govuk-elements.herokuapp.com/form-elements/example-date/) have a `max` attribute of 2016.

They were last updated in #175.

#### How would you expect it to work?

We could:

- Update the max attribute to a year far in the future (3000? 9999?)
- Remove the max attribute entirely

**Comment by joelanman** [comment]
My vote is to remove min and max. In general I don't think we should try and introduce validation into our coded patterns. For that to be done properly it needs to incorporate server side code. It also needs error massages relevant to the context, which we don't necessarily know.

On top of that, the min/max experience in the browser is odd. I can enter 2020 in the above example in desktop chrome and safari on MacOS, and it seems to accept it. If I then use keyboard up/down (not a feature I would expect most people to know about) it snaps to 2016.

**Comment by selfthinker** [comment]
I would also remove it entirely.
You also have to think about the developers who would use the date example for any date and not just date of birth, so they might end up having it in a year field which needs to be in the future.

**Comment by 36degrees** [comment]
Conversely, I wonder if it _would_ be helpful to add maxlength to the fields (2 for day and month, 4 for year). At the minute, you can type as many digits as you want into each box:

<img width="261" alt="screen shot 2018-03-02 at 11 08 57gmt" src="https://user-images.githubusercontent.com/121939/36896324-234f02a6-1e0a-11e8-861f-21ef39883bde.png">

**Comment by joelanman** [comment]
That seems safer, however it's still validation with no feedback, which worries me. Say someone misunderstood and started typing 'Jan' in the month, they'd type 'Ja' and then it would just 'stop working'. I think proper validation with messaging is always preferable

**Comment by edwardhorsford** [comment]
I suggest removing this limit. I think if a service *does* want to put min and max digits that's something they'll need to think about - it's safer for us to not include it in the examples (and we don't have to keep it up to date either).
