### ISSUE TITLE
SSH access

### ISSUE THREAD

**Issue by philipmclaughlin** [alphagov/govuk_elements#616]
Can I get ssh access to this project. I can't git clone the ssh repo - git@github.com:alphagov/govuk_elements.git

#### Explain the steps to reproduce the bug

1.
2.
3.
4.

#### Tell us about your environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by 36degrees** [comment]
Hi Philip,

GOV.UK Elements has been retired following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/). GOV.UK Elements is still available to you if you are currently using it but will no longer be maintained – it is only going to get major bug fixes and security patches going forward.

If you do need to use GOV.UK Elements for whatever reason, there are two ways you can clone a repo on GitHub – using `ssh` or using `https`. Based on what you've told me I suggest the easiest thing will be to clone over `https`.

If you do need to use ssh, you'll need to generate an SSH keypair on your computer and add the public key to your GitHub account. 

GitHub has [documentation which can help you with both of these](https://help.github.com/articles/which-remote-url-should-i-use/).

I'm going to close this issue as I believe I've answered your question, but please feel free to re-open it if you have any questions or continue to have issues.
