### ISSUE TITLE
Central Style guide

### ISSUE THREAD

**Issue by pflannery** [alphagov/govuk_elements#73]
Hi. 

I've been working on the Department for Education School Perf. Tables (Alpha now moving to Beta) and wanted to ask if there is a central style guide for all the gov uk components etc.

So far I've found style guides like this http://rural-payments-styleguide.herokuapp.com/elements/snippets/#layout which gives us a lot structure but no skin  separation and no javascript examples plus its navigation is a bit painful for the less front end savy dev's.

I come from an OOCSS background where structure and skin is separated. We have three projects here that we want to skin but maintain a gov uk structure plus we have extra feature rich components like maps, mobile swipe interactions etc etc.

I'm now looking to build a style guide during our beta journey that gives the less front end savy developers a easy way to just grab html, js etc.. and get on. So what I'm trying to find is a one stop shop that gives us the following ability:

  - a style guide build tool process (like hologram) lets us integrate our skins with the gov uk sass components and generate a style guide which we host on each published DFE website
  - The style guide should contain overview\description of each (most) components, html and js examples etc..
  - simple navigation for less front end savy dev's to find what they need

Is there any such place the fulfils this?

**Comment by cjforms** [comment]
hi Peter
We've been talking recently about the best way to support developers and designers, so it's helpful to know that you've been thinking about it too. 

Two of the key people are away next week but I'll keep a note of this and will remember to raise it with them on their return.

**Comment by pflannery** [comment]
Cool thanks

**Comment by gemmaleigh** [comment]
Hi @pflannery, are you happy to close this issue?

**Comment by pflannery** [comment]
I'm happy to close.
