### ISSUE TITLE
Add example of search box with inline search button

### ISSUE THREAD

**Issue by henryhadlow** [alphagov/govuk_elements#83]
We use these everywhere – e.g. www.gov.uk homepage, all other pages in the header

Can we add one to this repo?

**Comment by cjforms** [comment]
We use them but how convinced are we that they're a good pattern?



Caroline Jarrett
User researcher / forms specialist
Government Digital Service

Twitter @cjforms
07990 570647

My GDS days are usually Monday to Wednesday.

**Comment by gemmaleigh** [comment]
We have this on the Hackpad: 
https://designpatterns.hackpad.com/Search-buttons-mfVImR30c7G

@henryhadlow did you want an example of a search box within the GOV.UK header? If so, this should really be part of the GOV.UK template.

**Comment by gemmaleigh** [comment]
Hi @edds what's the history of the search box in the header? It's not currently part of the GOV.UK template.

**Comment by 36degrees** [comment]
Following the launch of the [GOV.UK Design System](https://design-system.service.gov.uk/), GOV.UK Elements will now only get major bug fixes and security patches, so I'm going to close this.

There is an [issue in the Design System backlog for search boxes](https://github.com/alphagov/govuk-design-system-backlog/issues/132) which has some more discussion around the search box component.
