### ISSUE TITLE
we should probably change the content of the grid example

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#84]
https://github.com/alphagov/govuk_elements/blob/master/views/examples/grid_layout.html

**Comment by gemmaleigh** [comment]
This has been updated. 
http://govuk-elements.herokuapp.com/examples/grid-layout/

**Comment by TFOH** [comment]
Hi the link you provided doesnt work @gemmaleigh

**Comment by gemmaleigh** [comment]
@TFOH thanks for spotting this - that's been fixed - it's working now.

**Comment by TFOH** [comment]
@gemmaleigh I noticed a few of the other example pages were offline, sorry i can't be more specific, you may have fixed this now. However I just checked and 'http://govuk-elements.herokuapp.com/snippets/' is still offline.

**Comment by gemmaleigh** [comment]
@TFOH the snippets have been moved, so you can now find these underneath each example.

**Comment by TFOH** [comment]
@gemmaleigh thanks for the update, I was actually using the snippets page URL for reference at the time it was taken down earliewr, and I was highly confused as to why the page wouldn't reload, but this would be a very good explanation as to why!
