### ISSUE TITLE
Could we add a 'binary' class for yes no buttons?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk_elements#88]
Proposal:

Add a `binary` class so that yes/no buttons sit next to each other even on small screens.

Currently:

<img width="309" alt="screen shot 2015-07-15 at 17 44 42" src="https://cloud.githubusercontent.com/assets/1132904/8704264/da5a57a2-2b19-11e5-9781-5e8340d07757.png">

Proposed:

<img width="308" alt="screen shot 2015-07-15 at 17 47 05" src="https://cloud.githubusercontent.com/assets/1132904/8704269/e49f8a70-2b19-11e5-9166-d3dc286adc2a.png">

**Comment by gemmaleigh** [comment]
I'm not sure `.binary` is the clearest of classes to use in this case, we already have an `.inline` parent class which will sit both labels next to each other, however they sit underneath each other for smaller screens.

But you're right - we should have an example where Yes / No options remain next to each other for mobile and up.

cc. @joelanman @edwardhorsford (summarising our conversation on Slack).

**Comment by joelanman** [comment]
Some points raised on slack:

 - It'd be nice if the elements had 50%/50% widths to fit the screen
 - Is it just yes/no - or should eg. date fields be inline on mobile?

**Comment by edwardhorsford** [comment]
Yep, I'd be worried about the confusion as they do very similar things.

If it's for a very specific case, I support having specific class names. Eg:
* pattern-yes-no
* pattern-uk-address
* pattern -postcode

Each of these could have very specific styling that we know works for these elementss.

**Comment by robinwhittleton** [comment]
No-one’s talked about the features requested in this bug (over and above those provided by `.inline`) any time recently. Is it still something people want?

**Comment by joelanman** [comment]
I still think having certain things inline on mobile would be good.
